tensorflow/docs

site/en/tutorials/keras/overfit_and_underfit.ipynb

Formula in code for L2 weight regularization: https://github.com/keras-team/keras/blob/23bdd4d417f0fda90465e3ab612c682e1d207ee3/keras/regularizers.py#L42

Fix the description of the L2 weight regularization example

---

site/en/extend/adding_an_op.md

Minor doc fixes:
* Errant `\` in example code
* Case sensitive anker link

Adding-op doc fixes

---

site/en/api_guides/python/math_ops.md
site/en/community/roadmap.md
site/en/guide/autograph.ipynb
site/en/guide/premade_estimators.md
site/en/guide/saved_model.md
site/en/install/install_sources.md
site/en/install/install_sources_windows.md
site/en/performance/xla/jit.md
site/en/performance/xla/operation_semantics.md
site/en/tutorials/keras/basic_regression.ipynb
site/en/tutorials/keras/basic_text_classification.ipynb
site/en/tutorials/keras/overfit_and_underfit.ipynb

Sync in the last few changes that were submitted during the docs move.

Sync contents

---

site/en/hub/README.md
site/en/probability/README.md

Placeholder and link for subsites.

Subsite stubs

---

site/en/mobile/README.md

Add stub and link for tf lite

---

site/en/tutorials/_index.yaml
site/en/tutorials/eager/index.md

Use relative links for eager notebooks

---

site/en/guide/using_tpu.md

 Fix link and update TPU What's Next section

---

site/en/guide/autograph.ipynb

This autograph guide is broken on nightly. replacing `range` with `tf.range` works 
cc: @mdanatg

Created using Colaboratory

---

site/en/install/install_linux.md

Link to Nvidia driver download page is currently broken. This PR fixes it.

Fix link to Nvidia GPU driver page

---

site/en/tutorials/eager/custom_training_walkthrough.ipynb

fix test file path in eager/iris

---

site/en/performance/model_optimization.md
site/en/tutorials/_index.yaml
site/en/tutorials/next_steps.md

Update docs for TF Lite

---

site/en/tutorials/_index.yaml
site/en/tutorials/_toc.yaml

downcase yaml booleans

---

site/en/tfx/_book.yaml
site/en/tfx/_index.yaml
site/en/tfx/_project.yaml
site/en/tfx/_redirects.yaml

Add tfx/ files

---

site/en/install/source.md

Fixes https://github.com/tensorflow/tensorflow/issues/22475

Fix bazel version for tf-gpu

---

site/en/deploy/_toc.yaml
site/en/deploy/deploy_to_js.md
site/en/deploy/hadoop.md
site/en/deploy/index.md
site/en/deploy/leftnav_files
site/en/deploy/s3.md

Edits to hadoop.md.
Convert leftnav_fiels to toc.yaml and update titles.
From https://github.com/tensorflow/docs/pull/74

Deploy section

---

site/en/tutorials/keras/basic_text_classification.ipynb

Fix a typo in docs

---

site/en/tutorials/_index.yaml

See: cl/211871776
Confirmed staging w/ style

Update tutorials/_index.yaml formatting

---

site/en/install/pip.html

Add URLs to Windows pip packages

---

site/en/api_docs/_book.yaml
site/en/api_docs/index.md
site/en/swift/_book.yaml
site/en/swift/_index.yaml
site/en/swift/_project.yaml

Swift subsite landing page

---

site/en/tutorials/eager/eager_basics.ipynb

Changed '`N`th tensor' to '`N`th GPU'.
Also made small typographical fixes -- consistency of caps for 'Tensor' and added newline to render markdown bullets.

Fixed error in 'Device Names' section on Eager execution basics

---

site/en/tutorials/eager/custom_training_walkthrough.ipynb

Fix url target for logits

---

site/en/tutorials/keras/save_and_restore_models.ipynb

Most of the diff is because Colab changed their Save format. Actual content change is around line 500.

Use tf.train.latest_checkpoint

---

site/en/swift/_book.yaml
site/en/tutorials/sequences/text_generation.ipynb

Fix lint errors

---

site/en/guide/estimators.md

* Added spaces around dashes
* Fixed broken estimators tutorial link
* Added white paper link

Update estimators guide

---

CODEOWNERS

Will need to remove from copybara sync

Add default owners for repo

---

site/en/tutorials/eager/custom_training.ipynb

tf.Variable works in r1.12
These are the only ones.
grep tfe.Variable -r .

tfe.Variable --> tf.Variable

---

site/en/tutorials/eager/automatic_differentiation.ipynb

(Line 315)
https://colab.sandbox.google.com/github/markdaoust/docs/blob/fix-autodiff/site/en/tutorials/eager/automatic_differentiation.ipynb

This was broken. Use Variable for automatic watch.

---

site/en/guide/performance/benchmarks.md

Fix links benchmark images

---

site/en/api_docs/_book.yaml
site/en/guide/_toc.yaml
site/en/guide/extend/cc.md
site/en/guide/version_compat.md

And remove the api_guides/cc directory.

Move C++ guide to /guide/extend/cc

---

site/en/api_guides/python/math_ops.md

from c02bb5a4c2856ff6ffbe16dbeff62049dd655842^
There are a bunch of references to the segmentation section, we should keep it until segmentation has a better home.

restore math_ops.md 

---

site/en/tfx/_book.yaml
site/en/tfx/api_docs/index.md

Update toc for tfma

---

site/en/install/docker.md
site/en/install/pip.html

Fixes https://github.com/tensorflow/tensorflow/issues/23261

Update TF snippet to verify install

---

site/en/tfx/_book.yaml
site/en/tfx/api_docs/index.md

Update TFX docs

---

site/en/guide/extend/architecture.md

Fix reference for nccl_ops.py

---

site/en/tutorials/load_data/tf-records-and-examples.ipynb
site/en/tutorials/load_data/tf-records.ipynb

Working with Josh to get the first version of this tutorial checked in. Please let me know if you have any suggestions, happy to make changes.
Direct Links: [GitHub](https://github.com/raskutti/docs/blob/master/site/en/tutorials/load_data/tf-records.ipynb), [Colab](https://colab.sandbox.google.com/github/raskutti/docs/blob/master/site/en/tutorials/load_data/tf-records.ipynb)

Adding tf.Example and TFRecords tutorial.

---

site/en/tutorials/sequences/text_generation.ipynb

fix var name.

---

site/en/install/errors.md
site/en/install/source_windows.md

Please, consider merging this to help ones who are trying to build on windows from source and are getting error at package creation stage related to this https://github.com/tensorflow/tensorflow/issues/22390

Added documentation on workaround for issue #22390 when building on windows

---

site/en/tfx/_index.yaml

Adding TFDV blog post to landing page and reordering components for consistency

Adding TFDV blog post to landing page

---

site/en/install/_index.yaml

Match CSS/yaml for install/_index

---

site/en/tfx/_index.yaml

Clemens wanted TFMA before TFS, which I guess makes sense.

TFMA before TFS

---

site/en/tfx/_book.yaml
site/en/tutorials/sequences/text_generation.ipynb

Update TFX translation config

---

site/en/install/source_windows.md
site/en/lite/README.md
site/en/tfx/README.md
tools/release_tools/update_versions.py
tools/setup.py
tools/tensorflow_docs/api_generator/doc_controls.py
tools/tensorflow_docs/api_generator/doc_generator_visitor.py
tools/tensorflow_docs/api_generator/doc_generator_visitor_test.py
tools/tensorflow_docs/api_generator/generate_lib.py
tools/tensorflow_docs/api_generator/public_api.py
tools/tensorflow_docs/api_generator/public_api_test.py
tools/tensorflow_docs/api_generator/traverse.py
tools/tensorflow_docs/api_generator/traverse_test.py

PiperOrigin-RevId: 222102227

---

site/en/api_docs/_book.yaml
site/en/community/documentation.md
site/en/swift/_book.yaml
site/en/swift/_index.yaml
site/en/tfx/_book.yaml
site/en/tfx/_index.yaml
site/en/tutorials/next_steps.md

Rename ecosystem to resources

---

site/en/2/guide/_tf2.ipynb

Broke with the latest nightly due to updates in saved_model.export tags

Fix v1 loader shim

---

site/ko/tutorials/keras/basic_classification.ipynb

If you prepare the process for translation, I will make more PR.
I translated some ML/DL books to Korean(Francois Chollet's book, Aurelien Geron's book, Andreas Muller's book), so I can help you to review other Korean translation PR.

KO translation - basic_classification.ipynb

---

tools/tensorflow_docs/api_generator/generate_lib.py

Sync all generated files to output dir.

---

site/en/tutorials/_index.yaml

Add index code snippet callout box.

---

site/en/install/source.md
site/en/install/source_windows.md

Update required packages version as same as `setup.py`.

Update required packages version

---

site/en/2/guide/upgrade.md
site/en/tutorials/representation/unicode.ipynb

COPYBARA_INTEGRATE_REVIEW=https://github.com/tensorflow/docs/pull/219 from 0101011:master 90a369e2d83de37f55ba35bb9fdc1dd4f821215b
PiperOrigin-RevId: 225845602

Sync to github

---

site/en/guide/keras.ipynb

added weights_only html reference tag

---

site/en/2/guide/effective_tf2.md

(with the activation in there, better to call this a dense layer)

Renaming linear -> dense

---

site/en/tutorials/keras/overfit_and_underfit.ipynb

Fix typos in overfit and underfit tutorial

---

site/ru/tutorials/keras/save_and_restore_models.ipynb

Random thoughts:
🔴 Got to find a way to bulk edit broken or outdated links across multiple folders
🔴 Or to automate somehow

housekeeping with @rickiepark

---

site/en/tutorials/keras/basic_regression.ipynb

Fix a typo in regression tutorial

---

site/en/guide/keras.ipynb

Met those while translating, proposing fixes:

various comments

---

site/en/guide/debugger.md

Fixed a minor typo for the tfdbg guide

---

site/en/2/tutorials/eager/custom_training_walkthrough.ipynb

Since TF 2.0 does not require enabling eager, this sentence can be removed.
"and enable eager execution for this program"

Remove enable eager from the text

---

site/en/2/tutorials/keras/basic_regression.ipynb

Corrected a sentence from "predict some housing prices" to "predict fuel efficiency"

Corrected a sentence

---

site/en/2/tutorials/eager/eager_basics.ipynb

since tf 2.0 does not require enable eager execution

typo fixes removed "and enable eager execution"

---

site/en/2/tutorials/keras/index.md

fixed the broken links

---

site/en/r2/tutorials/keras/basic_classification.ipynb

Executing the cell containing `model.evaluete()` displays `Text accracy` in the same line of the progress bar like below.
```
8544/10000 [========================>.....] - ETA: 0s - loss: 0.3356 - acc: 0.8794Test accuracy: 0.8787
`
I added newline before `Test accuracy:`.

cosmetic change for test accuracy display.

---

site/en/tutorials/keras/index.md

Updated the link to the notebooks provided as tutorials

fix broken link

---

site/en/r2/tutorials/eager/index.md

updated eager execution link []https://github.com/tensorflow/tensorflow/issues/24856

updated eager execution link

---

site/en/guide/custom_estimators.md

Update train_input_fn code in custom estimators

---

site/en/r2/guide/upgrade.md

Fix wrong version in upgrade instructions

---

site/en/guide/estimators.md

1. `my_training_set` is not a function (see line 115).
2. Propose changing ‘input_fn’ to `data_input` in the whole block of text as a more explicit function name and to improve readability.
Input function traditionally expects some input from a user whereas in our context data loading and manipulation might be more relevant.

Estimators: comment fix + better name proposed

---

site/en/r2/tutorials/keras/overfit_and_underfit.ipynb

The code in the notebook was a little messy. Refactored the code to make it more modular and readable. Also, the text cells in the notebook have been updated to include more clear documentation.

Code refactor and updat doc

---

site/en/install/source_windows.md

Added mention to the second page of configuration instructions for C++

Changed bazel install instructions

---

site/en/r2/tutorials/generative/image_captioning.ipynb

Just a fix for leftovers from version 1

Fix image_load accordingly with TF2 API symbols

---

site/en/guide/performance/overview.md

change :%s/Alexnex/Alexnet/
Fixes #25397
Signed-off-by: Rahul Nair <rahulunair@gmail.com>

Fixes documentation nit

---

site/ko/README.md
site/ko/tutorials/keras/basic_classification.ipynb
site/ko/tutorials/keras/basic_regression.ipynb
site/ko/tutorials/keras/basic_text_classification.ipynb
site/ko/tutorials/keras/index.md
site/ko/tutorials/keras/overfit_and_underfit.ipynb
site/ko/tutorials/keras/save_and_restore_models.ipynb

I updated a disclaimer and added words not to be translated.
Thanks.

Update a disclaimer in site/ko/

---

site/ko/r2/tutorials/keras/basic_classification.ipynb
site/ko/r2/tutorials/keras/basic_regression.ipynb
site/ko/r2/tutorials/keras/basic_text_classification.ipynb
site/ko/r2/tutorials/keras/index.md
site/ko/r2/tutorials/keras/overfit_and_underfit.ipynb
site/ko/r2/tutorials/keras/save_and_restore_models.ipynb

This notebooks are mostly identical to ko/tutorials/keras.
But It is updated with changes in en/r2/tutorials/keras.
Running with Colab is OK.
Thanks.
@lamberta , I will continue translating `en/r2/tutorials/beginner`. :)

Add ko/r2/tutorials/keras notebooks

---

site/en/r2/tutorials/keras/basic_classification.ipynb
site/en/tutorials/keras/basic_classification.ipynb

use  `plt.show()` for ploting example, like in chapter "Preprocess the data"

improved example, basic_classification

---

site/ko/r2/guide/effective_tf2.md

Korean Translation of effective_tf2.md
I will update it in a while for proofreading.
Thanks.

KO: translate ko/r2/guide/effective_tf2

---

site/en/guide/ragged_tensors.ipynb

Fix typo in ragged_tensors.ipynb

---

site/ko/r2/guide/effective_tf2.md

Update tf.summary section based on 4fc39442bfa5cebb8a7a220f50f76c7030a31aa6, 6933aaef4062dd6b09b010e70e8c720a49ac9137.
Thanks.

KO: update tf.summary section in effective_tf2.md

---

site/ko/hub/README.md

I translated the hub document into Korean.

Add ko hub

---

site/en/tutorials/keras/basic_classification.ipynb

- Add explicit code to show the plotted value array for the single prediction.
- Add explicit code to print the prediction label value for the single prediction.

Make code more explicit

---

site/ko/tutorials/keras/basic_classification.ipynb

Update tutorial/keras/basic_classification.ipynb based on c1bec0cd18e7b4b407e2afecb309d21c7b60f7fa and check with Colab.
Thanks!

KO: update ko/tutorial/keras/basic_classification.ipynb

---

site/en/guide/saved_model.md

Fixes Issue [#26431](https://github.com/tensorflow/tensorflow/issues/26431)

Update saved_model.md - Fixes dead link

---

site/en/r2/tutorials/images/intro_to_cnns.ipynb

See https://github.com/tensorflow/tensorflow/issues/26470

Fixes broken link in CNNS tutorial #26470

---

site/en/tutorials/sequences/recurrent.md

Fixes Issue [#26469](https://github.com/tensorflow/tensorflow/issues/26469)

Fixes Broken Link

---

site/ko/alpha/guide/effective_tf2.md

fix apply_graidents to take a list of tuple

KO: update alpha/guide/effective_tf2.md

---

site/ko/README.md
site/ko/alpha/guide/keras/overview.ipynb
site/ko/alpha/tutorials/keras/basic_classification.ipynb
site/ko/alpha/tutorials/keras/basic_regression.ipynb
site/ko/alpha/tutorials/keras/basic_text_classification.ipynb
site/ko/alpha/tutorials/keras/index.md
site/ko/alpha/tutorials/keras/overfit_and_underfit.ipynb
site/ko/alpha/tutorials/keras/save_and_restore_models.ipynb
site/ko/tutorials/keras/basic_classification.ipynb
site/ko/tutorials/keras/basic_regression.ipynb
site/ko/tutorials/keras/basic_text_classification.ipynb
site/ko/tutorials/keras/index.md
site/ko/tutorials/keras/overfit_and_underfit.ipynb
site/ko/tutorials/keras/save_and_restore_models.ipynb

Remove https://bit.ly/tf-translate link and change a term to common word.
Thanks! :)

KO: Update the disclaimer

---

site/ja/README.md

Added a Japanese README with the community translation disclaimer.

added site/ja/README.md

---

site/ko/alpha/guide/effective_tf2.md

I definitely missed the proofreading of this two lines. :(
Thanks!

KO: update ko/alpha/guide/effective_tf2.md

---

site/ru/README.md

1. Better wording 😊
2. Putting a warning sign about underscore docs being still in development and won't be pulled yet

RU: Readme.md - Added underscore docs notice

---

site/ko/tutorials/eager/_style_transfer.ipynb

Start translate index.md, _style_transfer.ipynb 
I'm going to translate en/tutorials/eager
@rickiepark

KO: translation ko/tutorials/eager/_style_transfer.ipynb

---

site/tr/README.md

@ilkaynazli Please take a look.

README file for turkish translations.

---

site/en/r2/guide/keras/custom_layers_and_models.ipynb

In TensorFlow 2.0, we could use simple if statement instead of tf.cond for better understanding. It also gets rid of those lambda functions.

Changing tf.cond by if statement in custom_layers_and_models.ipynb

---

site/ko/README.md

Add docs-ko mailing list.
Thanks!

KO: update ko/README.md

---

site/en/r2/tutorials/eager/custom_layers.ipynb
tools/templates/subsite/g3doc/_project.yaml
tools/templates/subsite/g3doc/api_docs/README.md

I just found that some sentence is used twice in custom_layers.jpynb.
1. en/tutorials/eager(line 237-8 (check line 199)).
2. en/r2/tutorials/eager(line 247-8 (check line 209)).
Thanks :)

EN: Fix duplicated sentence in custom_layers.jpynb

---

site/en/tutorials/images/hub_with_keras.ipynb

comvert -> convert
Thanks for the tutorial!

doc: fix typo

---

site/en/r2/tutorials/keras/index.md

Th issue was https://github.com/tensorflow/tensorflow/issues/27615
Updated Index.md with proper links.
Earlier the link was redirecting to an Error 404.

Solves the issue as Mentioned in #27615

---

site/ru/REVIEWERS

1. Saw the brand new tfdocsbot yesterday, looking good!
2. Will be back in 7 days with some new sequences docs for RU

RU: Adding A. Stepin to reviewers list

---

site/en/install/source_windows.md

Fixes https://github.com/tensorflow/tensorflow/issues/27575

Added bazel version specific message

---

site/ko/alpha/guide/migration_guide.ipynb
site/ko/alpha/tutorials/keras/index.md

Update `ko/alpha/guide/migration_guide.ipynb` and `ko/alpha/tutorials/keras/index.md`.
Thanks!

KO: Update to sync with en

---

site/en/r2/tutorials/estimators/boosted_trees_model_understanding.ipynb

Added a missing period to the end of a sentence.

Added missing period

---

site/en/install/pip.html

Confirmed in https://github.com/tensorflow/tensorflow/issues/17022

Update pip install to Py 3.7

---

site/en/r2/tutorials/load_data/images.ipynb

About the shuffling, I'm quite sure you need to shuffle after repeating in order to get cross-epoch shuffling. Please let me know if this is not the case.

Minor fixes in image data loading.

---

site/ko/REVIEWERS

Hi @lamberta , added my github username. Thank you!

KO: add reviewer to ko/REVIEWERS

---

site/tr/README.md
site/tr/tutorials/keras/basic_classification.ipynb
site/tr/tutorials/keras/basic_regression.ipynb
site/tr/tutorials/keras/basic_text_classification.ipynb
site/tr/tutorials/keras/index.md
site/tr/tutorials/keras/overfit_and_underfit.ipynb
site/tr/tutorials/keras/save_and_restore_models.ipynb

Following notebooks are translated to Turkish;
-basic_regression.ipynb
-overfit_and_underfit.ipynb
-save_and_restore_models.ipynb
Other files in the folder has been translated already with PR #428
-basic_classification.ipynb
-basic_text_classification.ipynb
-index.md

Turkish Translation of en/tutorials/keras Folder - Part 2/2

---

site/en/tutorials/images/hub_with_keras.ipynb

Fixing minor typo on https://www.tensorflow.org/tutorials/images/hub_with_keras

fix minor typo

---

site/ja/REVIEWERS

Please add me to  site/ja/REVIEWERS

JA: Add masa-ita to reviewers list

---

site/en/r2/tutorials/load_data/images.ipynb
site/en/tutorials/load_data/images.ipynb

The images didn't show up when I ran this example in Google Colab... like the docs showed. So figured I'd submit a PR.
Any questions or comments let me know please.

plt.show() needs to be called to see the images

---

site/en/r2/tutorials/quickstart/advanced.ipynb

Use plural for images and labels to make clear that we
are working with a batch and not a single instance

Update tf2 advanced tutorial to use plural for batches

---

site/en/r2/tutorials/images/hub_with_keras.ipynb

updated button links and link to hub

Hub w/ Keras r1 -> r2

---

site/en/tutorials/images/hub_with_keras.ipynb

Some references to tf2 removed

Hub w/ Keras r2 -> r1

---

site/ko/README.md

Change notification guide from Github's draft PR to docs-ko mailing list.

[KO] update site/ko/readme.md

---

site/zh-cn/tutorials/keras/basic_classification.ipynb
site/zh-cn/tutorials/keras/index.md

zh-ch: add Chinese translation of `site\zh-cn\tutorials\keras\index.md` && `site\zh-cn\tutorials\keras\basic_classification.ipynb`

zh-CN: add Chinese translation for 2 files

---

site/ja/r2/tutorials/keras/basic_classification.ipynb
site/ja/r2/tutorials/keras/basic_regression.ipynb
site/ja/r2/tutorials/keras/basic_text_classification.ipynb
site/ja/r2/tutorials/keras/feature_columns.ipynb
site/ja/r2/tutorials/keras/index.md
site/ja/r2/tutorials/keras/overfit_and_underfit.ipynb
site/ja/r2/tutorials/keras/save_and_restore_models.ipynb

I've translated files (a markdown file and notebooks) in site/ja/r2/tutorials/keras.

JA: added translated files in site/ja/r2/tutorials/keras

---

site/ko/alpha/guide/effective_tf2.md

Update from 89a4147dfab3a772dcaa135360f48af86f90fbfe
(tape.gradients --> tape.gradient)

[KO] update site/ko/alpha/guide/effective_tf2.md

---

site/ko/alpha/tutorials/quickstart/advanced.ipynb
site/ko/alpha/tutorials/quickstart/beginner.ipynb

Translate advanced.ipynb & beginner.ipynb
Colab check is done.
Please review it! :)

[KO] translate site/ko/alpha/tutorials/quickstart

---

site/ja/guide/keras.ipynb

translation in progress.
https://github.com/tensorflow/docs/blob/master/site/en/guide/keras.ipynb

JA: translation site/ja/guide/keras.ipynb

---

site/en/r2/tutorials/text/transformer.ipynb

Fixed some type.

---

site/en/r2/tutorials/distribute/keras.ipynb

Since tensorflow_datasets is a standalone module and users are required to install it separately in their local session (not using colab) the current notebook will throw error complaining tensorflow_datasets module not found.
By adding tensorflow_datasets installation to existing notebook users will be able to execute the code as is without additional module installation.

Suggestion to update keras.ipynb by adding tensorflow_datasets installation

---

site/en/r2/tutorials/quickstart/beginner.ipynb

For the HTML version, clarify user needs to do steps in Colab.

Edit to beginner file

---

site/ko/alpha/tutorials/images/intro_to_cnns.ipynb

Translate site/en/r2/tutorials/images/intro_to_cnns.ipynb to site/ko/alpha/tutorials/images/intro_to_cnns.ipynb.
Thanks!

[KO] translate site/en/r2/tutorials/images/intro_to_cnns.ipynb

---

site/ko/alpha/tutorials/keras/basic_text_classification.ipynb
site/ko/alpha/tutorials/keras/overfit_and_underfit.ipynb

update from 09ee44669153ca2964a806e9064f3057e79eb7a7
(Because the problem when load pickling object in numpy 1.16.3)

[KO] update site/ko/alpha/tutorials/keras

---

site/zh-cn/js/guide/index.md

zh-ch: translation /js/guide/index.md

---

site/ja/r2/guide/autograph.ipynb

Translate https://github.com/tensorflow/docs/blob/master/site/en/r2/guide/autograph.ipynb

JA : translation r2/guide/autograph.ipynb

---

site/ko/README.md

Translate TF2-only announcement.
Thanks!

[KO] Translate TF2-only announcement in site/ko/README.md

---

site/en/tutorials/distribute/training_loops.ipynb

MirroredStrategy reduce doesn't have axis parameter

Fix MirroredStrategy reduce bug

---

site/en/install/pip.html

See [#27435](https://github.com/tensorflow/tensorflow/issues/27435). Removed tf.enable_eager_execution(). Change tf.random_normal to tf.random.normal

#27435 Fix Verify installation scripts for eager execution and aliases

---

site/en/r2/tutorials/load_data/numpy.ipynb

New notebook: Load from numpy

---

site/en/community/contribute/docs.md

Added links to the worldwide map with events, and to the attendee cheatsheet.

Added a section for the TF 2.0 Global Docs Sprint

---

site/en/r2/guide/keras/overview.ipynb
site/en/r2/tutorials/keras/basic_regression.ipynb

(1) Worked on Keras Overview; (2) Changed wording and case of title of regression example topic.

Clarity edits

---

site/en/tutorials/keras/basic_text_classification.ipynb

Fixes a broken link issue (related to pad_sequences) reported in this [issue](https://github.com/tensorflow/tensorflow/issues/29358).

broken link related to pad_sequences

---

site/ko/README.md

Korean community now use a spreadsheet to manage translations with google groups.
I update README file for the spreadsheet.
Thanks!

KO: Add a translation status spreadsheet to README

---

site/en/guide/distribute_strategy.ipynb

Found successive "below" in the document, so removed it.

Fixed duplicate words

---

site/zh-cn/js/guide/conversion.md

The changes have been added from the last review and I made a few changes.

Zh-cn_js_guide_conversation.md

---

site/ru/beta/_index.yaml

Draft translation to Russian of _index.yaml

RU: translation of _index.yaml

---

site/en/r2/tutorials/distribute/training_loops.ipynb

My attempt at parsing the note might not be fully accurate.

Dense note paragraph --> H4 section

---

site/en/community/groups.md

add more Global Tensorflow communities.

Added more communities

---

site/en/r2/tutorials/text/nmt_with_attention.ipynb

Hello,
I found some confusing point in  https://www.tensorflow.org/alpha/tutorials/text/nmt_with_attention#write_the_encoder_and_decoder_model
I have added two reference paper in the explanation line.
Hope it will make the tutorial more clear.
Thanks

Kunxianhuang patch 1

---

site/en/guide/using_tpu.md

Typo's and errors corrected

---

site/pt/tutorials/keras/basic_classification.ipynb

Portuguese sentence correction

portuguese sentence correction

---

site/en/install/source.md
site/en/install/source_windows.md

This pr is to add an option to choose the usage of CPU.

Add options for CPU usage in the build process

---

site/en/tutorials/keras/overfit_and_underfit.ipynb

Prior issue fixed in 1.14 and nightly is breaking: https://github.com/tensorflow/tensorflow/issues/30261

Keras tutorial: use stable instead of nightly

---

site/zh-cn/REVIEWERS

- Add JayYip as Chinese doc reviewer

Add Chinese doc reviewer

---

site/en/community/groups.md

Per Billy's instructions, have added Houston TensorFlow & Applied AI/ML {by HCCUG.org™} to this page

Added Houston TensorFlow & Applied AI/ML {by HCCUG.org™}

---

site/en/r2/tutorials/load_data/images.ipynb

Some suggested improvements to the _'Load images with tf.data'_ tutorial:
- Rearrangement of words, fixing some grammar, addition/subtraction of commas/colons/spaces in English and Python for consistency [#30283](https://github.com/tensorflow/tensorflow/issues/30283)
If you find any of it useful or not so useful let me know @MarkDaoust @lamberta - any feedback welcome!

Update images.ipynb load data tutorial

---

site/pt/tutorials/keras/basic_regression.ipynb

This pull request brings the basic regression tutorial with keras translated to Portuguese - BR.

Translates basic_regression.ipynb to PT-BR

---

site/pt/REVIEWERS

I added my username to the list of reviewers. @lamberta I suggest renaming the folder "pt" to "pt-br" or even create a new folder to Brazilian Portuguese translations.

the first reviewer

---

site/ko/beta/tutorials/text/unicode.ipynb

Modify and proofread the file translated by @CamilaKim.
Checked it in Colab.
Thanks!

KO: translation of en/r2/tutorials/text/unicode.ipynb

---

site/en/r2/tutorials/text/unicode.ipynb

Just fix a typo (dedection --> detection).
Add spaces for proper indentation.
Thanks!

Fix a typo and add spaces in unicode.ipynb

---

site/ko/README.md
site/ko/swift/README.md

Update site/ko/README.md for S4TF docs and add another README.md in site/ko/swift.
Thanks!

KO: update and add README files

---

site/en/r2/tutorials/text/image_captioning.ipynb
site/en/r2/tutorials/text/text_generation.ipynb
site/en/tutorials/sequences/text_generation.ipynb

Changed loss function described in text cell to match one used in code cell

Fixed minor typo

---

site/ru/beta/tutorials/keras/basic_text_classification_with_tfhub.ipynb

Partially this document was used for translation: /tutorials/keras/basic_text_classification.ipynb

RU: translation of  beta/tutorial/keras/basic_text_classification_with_tfhub.ipynb

---

site/pt/tutorials/keras/basic_text_classification.ipynb

This pull request brings the basic text classification tutorial with keras translated to Portuguese - BR.

PT-BR: Translation of basic-text-classification.ipynb

---

site/zh-cn/lite/guide/android.md

zh-CN: android.md

---

site/zh-cn/REVIEWERS

Update zh-cn REVIEWERS

---

site/zh-cn/REVIEWERS

UPDATE: Update zh-cn REVIEWERS

---

site/fr/README.md
site/fr/REVIEWERS

Tensorflow needs a French translation
Create a directory `fr` in `site` with one README
WIP

Translation is French was abs

---

site/zh-cn/lite/convert/index.md

zh-CN:  translate   lite/convert/index.md

zh-CN:lite/convert/index.md

---

site/en/tutorials/eager/eager_basics.ipynb

Function tf.random_uniform not available. Revert to tf.random.uniform.

update to eager_basics.ipynb

---

site/fr/REVIEWERS

I added my username to ``REVIEWERS``

Adding my username

---

site/zh-cn/lite/microcontrollers/overview.md

Translated into Chinese:
`site\zh-cn\lite\microcontrollers\overview.md`

zh-CN: lite/microcontrollers/overview.md

---

site/zh-cn/lite/performance/benchmarks.md

zh-CN:lite/performance/benchmarks.md

---

site/zh-cn/lite/convert/cmdline_examples.md
site/zh-cn/lite/performance/benchmarks.md

zh-CN:lite/convert/cmdline_examples.md

---

site/zh-cn/lite/performance/gpu_advanced.md

translate   /lite/g3doc/performance/gpu_advanced.md

zh-CN: gpu_advanced.md

---

site/zh-cn/lite/guide/ops_select.md

translate ops_select.md into Chinese

zh-CN: ops_select.md

---

site/en/r2/tutorials/text/transformer.ipynb

use variable instead of the instance variable.

style mis-match

---

site/zh-cn/lite/microcontrollers/library.md

zh-CN:lite/microcontrollers/library.md

---

site/zh-cn/lite/performance/model_optimization.md

Please review the zh-CN:lite/performance/model_optimization.md
If there are any problems with this translation, please feel free to let me know.

zh-CN:lite/performance/model_optimization.md

---

site/zh-cn/lite/ convert/cmdline.md

Translation completes lite/convert/cmdline.md

zh-CN: lite/convert/cmdline.md

---

site/zh-cn/beta/tutorials/load_data/csv.ipynb

I have translated site/zh-cn/beta/tutorials/load_data/csv.ipynb with Chinese, please review it.

zh-CN: site/zh-cn/beta/tutorials/load_data/csv.ipynb

---

site/en/r2/tutorials/generative/cvae.ipynb

Implement graph-based acceleration for improved performance. Using google Colab this improved epoch times from ~ 30s / epoch to ~3.6s/ epoch. See associated issue : https://github.com/tensorflow/tensorflow/issues/31013#issue-472671053

Decorate with @tf.function

---

site/en/r2/tutorials/keras/basic_classification.ipynb

Suggestion to add class name index to x-axis

Add x-axis label for value plot

---

site/en/r2/tutorials/keras/basic_text_classification_with_tfhub.ipynb

Add direct link for `imdb_reviews`

Update link of imdb reviews dataset

---

site/ja/guide/keras.ipynb

Use pip install tensorflow=="1.*" to TF1 notebooks

Add pip install tensorflow==1.* for JA keras guide

---

site/en/r2/tutorials/quickstart/advanced.ipynb

Update the quickstart advanced tutorial to reset the loss and accuracy metrics every epoch.

Fix quickstart tutorial to reset metrics every epoch

---

site/ko/README.md

I corrected a typo in /ko/README.md.
If there is a problem with the fix, please let me know.
Thank you.

KO: Correct typos in site/ko/README.md

---

site/en/r2/guide/keras/custom_layers_and_models.ipynb

The loss formula in the comment doesn't match the loss added by a L2 regularizer.

Wrong loss formula in comment

---

site/en/r2/guide/keras/functional.ipynb

"None that the batch size..." --> "Note that the batch size..."

fix typo in keras functional API notebook

---

site/ja/REVIEWERS

Could you add me to reviewers list `site/ja/REVIEWERS`?

JA: Add AseiSugiyama to reviewers list

---

site/en/install/gpu.md

Add install instructions for cuDNN 7.6.2 and upgrade TensorRT.

cuDNN 7.6.2 18.04 and 16.04

---

site/en/install/docker.md

See here for context: https://github.com/tensorflow/tensorflow/issues/31926

Correct NVIDIA Docker installation instructions

---

site/ja/REVIEWERS

Can you add me to Japanese reviewers (site/ja/REVIEWERS)?

JA: Add yukinagae to Japanese reviewers

---

site/zh-cn/tutorials/keras/regression.ipynb

zh-CN:site/zh-cn/tutorials/keras/regression.ipynb
Create regression.ipynb, and update the latest en/ structure for TF2 docs
Please review the zh-CN:site/zh-cn/tutorials/keras/regression.ipynb
If there are any problems with this translation, please feel free to let me know.
Note: relate to https://github.com/tensorflow/docs/pull/942

zh-CN:site/zh-cn/tutorials/keras/regression.ipynb

---

site/ko/guide/keras/overview.ipynb

L1 to L2
korean translation version only
thank you

KO:Fix wrong character

---

site/ko/tutorials/distribute/multi_worker_with_keras.ipynb

Korean Translation of `Multi-worker training with Keras`.
Thank you for reviewing!

KO: translation for ko/tutorials/distribute/multi_worker_with_keras.ipynb

---

site/zh-cn/lite/models/segmentation/overview.md

zh-CN: segmentation/overview.md

---

site/en/tutorials/images/classification.ipynb

The model is not consistent with the comment above.
I was wondering which one was incorrect; between the comment and the model.
As my assumption, I changed the comment.
(I changed and tested the model as the comment mentioned, and got about 50% accuracy on the validation set.)

model inconsistency

---

site/es/tutorials/keras/classification.ipynb
site/es/tutorials/keras/regression.ipynb

Master es Keras Tutorials

---

site/en/tutorials/load_data/csv.ipynb

fix typo in csv.ipynb

---

site/ru/tutorials/keras/overfit_and_underfit.ipynb

I did smth weird when I tried to rebase my repo, so I close my pull requests fork repo again and open new pull request

RU: translation for tutorials/keras/overfit_and_underfit.ipynb

---

site/ja/REVIEWERS

Could you add me @nuka137 to Japanese reviewers?

JA: Add nuka137 to Japanese reviewers

---

site/ko/README.md

Fix README.md 

---

site/en/guide/keras/train_and_evaluate.ipynb

Output shape is (5, ) instead of (10, ), So fix the comment.

Fix the comment about the shape of output

---

site/en/tutorials/generative/style_transfer.ipynb

Fix typo in style_transfer.ipynb

---

site/en/community/groups.md

I added the TensorFlow Lagos group information to the community groups.

added tensorflow lagos to community groups

---

site/ja/REVIEWERS

@sfujiwara @masa-ita @ohtaman I added myself to japanese reviewers as we discussed in japanese community slack.

add chie8842 to japanese reviewers

---

site/en/tutorials/load_data/images.ipynb

Internal link to `#Performance` should be `#performance`

Fix broken anchor link

---

site/en/tutorials/keras/text_classification.ipynb

Fix typo in text_classification.ipynb

---

site/en/guide/distributed_training.ipynb

Adjust for BERT models move to /nlp folder

Update link in distributed_training.ipynb

---

site/zh-cn/tutorials/images/segmentation.ipynb

Finish translating segmentation.ipynb

zh-CN: segmentation.ipynb

---

site/en/guide/upgrade.ipynb

Fixed spelling mistakes

---

site/en/tutorials/images/classification.ipynb

In Create the model section,
thatr should be that
[issue #33830](https://github.com/tensorflow/tensorflow/issues/33830)

Typo in Create the model section,

---

site/en/tutorials/customization/custom_training_walkthrough.ipynb

Changed document links to tf2.0 APIs.
Fix optimizer from Adam to SGD.

Fix links and optimizer discrepancy with comments.

---

site/ja/tutorials/text/word_embeddings.ipynb

This pull request is a remake of PR #1090

JA: Add translated site/ja/tutorials/text/word_embeddings.ipynb

---

site/en/tutorials/generative/pix2pix.ipynb

use the BATCH_SIZE variable

---

site/en/tutorials/keras/regression.ipynb

Remove duplicate plt.axis at regression.ipynb

remove duplicate axis

---

site/en/tutorials/customization/custom_layers.ipynb

I found an small typo in tutorials/customization/

Corrected type at the documentation

---

site/en/tutorials/structured_data/imbalanced_data.ipynb

Fix merge conflict in https://github.com/tensorflow/docs/pull/1154

Corrected some spelling and grammar errors

---

site/it/README.md
site/it/REVIEWERS
site/it/tutorials/quickstart/advanced.ipynb
site/it/tutorials/quickstart/beginner.ipynb

Hello,
If you agree to it I would love to start a new branch of the translation of the documentation for the Italian language. In this PR I have created the folder `site/it` and the first two files `REVIEWERS` where I added myself and the translation of `README.md`.
Would it be ok to you that I start the Italian translation and work on it in the free time?

New translation: Italian

---

site/en/install/source.md

Added GPU and CPU headings which were missing in Linux section of Tested Build Configurations table.

Added missing headings.

---

site/en/r1/guide/checkpoints.md

fixed unclosed div tag in en/r1/guide/checkpoints.md

fixed unclosed div tag

---

site/ja/tutorials/text/text_classification_rnn.ipynb

This is a replaced PR of #1174.

JA: add site/ja/tutorials/text/text_classification_rnn.ipynb

---

site/zh-cn/tutorials/distribute/multi_worker_with_keras.ipynb

translate https://github.com/tensorflow/docs/blob/master/site/en/tutorials/distribute/multi_worker_with_keras.ipynb

zh-CN:translate tutorials/distribute/multi_worker_with_keras.ipynb

---

site/en/tutorials/load_data/images.ipynb

Fixed Windows runtime error 'slice index -1 of dimension 0 out of bounds.' because of Unix/windows different path separators.
Replaced '/' with os.path.sep
See [https://github.com/tensorflow/tensorflow/issues/32908#]

Fixed Windows runtime error 'slice index -1 of dimension 0' (#32908)

---

site/en/guide/data_performance.md

Address issue tensorflow/tensorflow#33048

Fix TFRecordDataset pattern globbing

---

site/en/guide/data.ipynb

Fixed typo

---

site/en/tutorials/keras/text_classification_with_hub.ipynb

While it's OK on Notebook
See [here](https://www.tensorflow.org/tutorials/keras/text_classification_with_hub#build_the_model).

Fix bad render on documentation website

---

site/en/community/groups.md

Replaced TensorFlow India UserGroup(shutdown) with TensorFlow Mumbai UserGroup(new group)

Added TF Mumbai UserGroup

---

site/en/r1/tutorials/sequences/audio_recognition.md

This pull request is related to [#34460](https://github.com/tensorflow/tensorflow/issues/34460).

fix download path

---

site/en/install/docker.md

This seems to be the simplest possible change to resolve https://github.com/tensorflow/tensorflow/issues/34758. I'm not totally certain it's the best change, though; I know it removes the errors described in the issue.

Remove eager-enabler since v2 has eager execution

---

site/en/guide/create_op.md

fix broken ref. links  in site/en/guide/create_op.md

fix broken ref. links in site/en/guide/create_op.md

---

site/zh-cn/tutorials/text/nmt_with_attention.ipynb

Translate https://github.com/tensorflow/docs/blob/master/site/en/tutorials/text/nmt_with_attention.ipynb
into Chinese.

Translate nmt_with_attention.ipynb into Chinese

---

site/ja/tutorials/load_data/pandas_dataframe.ipynb

original document:
[https://github.com/tensorflow/docs/blob/master/site/en/tutorials/load_data/pandas_dataframe.ipynb](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/load_data/pandas_dataframe.ipynb)

JA: add site/ja/tutorials/load_data/pandas_dataframe.ipynb

---

site/it/README.md

As agreed, updates split on different branches/files

IT: README.md - A typo and some untranslatable words added

---

site/id/CONTRIBUTING.md
site/id/REVIEWERS

Would like to be reviewers also contributor for this id translation. Adding file about guidelines for contributors.
Thanks

ID: Requesting to be part of reviewers

---

site/en/guide/keras/train_and_evaluate.ipynb

Fix simple typo in train_and_evaluate.ipynb

---

site/en/guide/data.ipynb

stradle -> straddle in site/en/guide/data.ipynb

Fix a typo

---

site/en/community/groups.md

Add TensorFlow Egypt

---

site/en/tutorials/text/text_classification_rnn.ipynb

This commit includes removing whitespace and changing parameter name.

Improve variable and convention

---

site/en/guide/function.ipynb

fix tf.config.run_functions_eagerly to tf.config.experimental_run_functions_eagerly

fix wrong tf function name

---

site/zh-cn/install/source_rpi.md

translate https://github.com/tensorflow/docs/blob/master/site/en/install/source_rpi.md

zh-CN:translate install/source_rpi.md

---

site/en/r1/tutorials/images/hub_with_keras.ipynb
site/en/tutorials/images/transfer_learning_with_hub.ipynb

Fix minor typos

---

site/fr/REVIEWERS

Added my username to REVIEWERS

Added my username to REVIEWERS

---

site/en/community/groups.md

Request to start a new TFUG chapter in India

New Chapter Request for Coimbatore

---

site/ko/tutorials/distribute/custom_training.ipynb

fixed a broken link of colab on the Korean translation.

fixed a broken link of colab

---

site/en/community/groups.md

Added TensorFlow Kolkata public meetup link.

Add TensorFlow Kolkata

---

site/zh-cn/datasets/overview.ipynb

translate https://github.com/tensorflow/datasets/blob/master/docs/overview.ipynb

[zh-CN] add chinese translation of datasets overview

---

site/en/community/groups.md

Request to start a new TFUG chapter in India

New Chapter Request for Kozhikode

---

site/en/tutorials/images/transfer_learning.ipynb

Ran through spell / grammar checker. Also changed all "fine tune" to contain hyphens – "fine-tune".

Spelling errors and grammatical errors

---

site/en/community/groups.md

Request to start a new TFUG chapter in India

New Chapter Request for Pune

---

site/en/tutorials/images/transfer_learning.ipynb

Fixes tensorflow/tensorflow#28718

Use an explicit loss function.

---

site/en/tutorials/keras/classification.ipynb

Fixes: https://github.com/tensorflow/tensorflow/issues/35249
https://www.tensorflow.org/tutorials/keras/classification#train_the_model
I've changed the accuracy on training data from 88% to 91%.
We get 88% for 5 epochs and 91% for 10 epochs and in tutorial above model is trained for 10 epochs.

Corrected accuracy value

---

site/en/tutorials/_index.yaml

The previous links are removed, need to update accordingly.

update the links for agents

---

site/it/tutorials/keras/classification.ipynb

Reference to translation done in PR #1232 with the proposed comments and typo fixes.

it - tutorial-keras-classification typos fix

---

site/ko/guide/keras/overview.ipynb

Thank you for providing the project.
I found a duplicate module while studying.
Thank you.

remove: duplicate module imports

---

site/ja/tutorials/text/word_embeddings.ipynb

Fix unexpected change from `padded_batch` to `padded_batch_2` caused by the commit https://github.com/tensorflow/docs/commit/32a74c85cb38bd5db15620a2d39b3dddd00c4d35

JA: Fix nonexistent method in ja/tutorials/text/word_embeddings.ipynb

---

site/en/tutorials/keras/text_classification_with_hub.ipynb

The previous one, https://github.com/tensorflow/datasets/blob/master/docs/datasets.md#imdb_reviews, is not available any more.

Update the imdb_reviews github link

---

site/zh-cn/tutorials/estimator/premade.ipynb

参照英文版，修改为：对于鸢尾花问题，`tf.estimator.DNNClassifier` 似乎是最好的选择

fix description for Instantiate an estimator

---

site/en/tutorials/text/image_captioning.ipynb

Model checkpoint has been added but the notebook does not contain any restoring code.

Restore the model from latest checkpoint

---

site/it/REVIEWERS

Hi everyone I would like to contribute to the translation of the TensorFlow documentation to Italian, so I add myself as reviewer :)

it - add maryggiannella to reviewers

---

site/en/guide/keras/train_and_evaluate.ipynb

Add from_logits=True to loss function in tf.GradientTape example. The code is broken without it.
ALLOW_H5=true

Fix loss function bug in GradientTape example

---

site/en/tutorials/keras/save_and_load.ipynb

typo in save_and_load.ipynb

---

site/en/guide/keras/functional.ipynb

`img_inputs` is not used in this notebook.
I think it must be `inputs`. :)
Thanks.

Fix variable name

---

site/en/r1/tutorials/distribute/tpu_custom_training.ipynb

The original notebook is not compatible with the Colab default Tensorflow 2. It also has two errors. This PR fixes these problems.

fix multiple errors

---

site/en/tutorials/quickstart/advanced.ipynb
site/en/tutorials/quickstart/beginner.ipynb

Context: https://github.com/tensorflow/tensorflow/issues/36595

Add callout note in quickstart tutorials to upgrade pip

---

site/en/tutorials/keras/save_and_load.ipynb

Specifically mentioned about the issue [#36861](https://github.com/tensorflow/tensorflow/issues/36861). Also, fixed the indentation. @jvishnuvardhan , Please review this.

Modified doc for specifically mentioning about saving optimizer

---

site/en/tutorials/images/classification.ipynb

fixes markdown typo

---

site/en/install/pip.html

Fix https://github.com/tensorflow/tensorflow/issues/36588
[TF 2.1 release](https://github.com/tensorflow/tensorflow/releases/tag/v2.1.0) brings in this new dependency requirement

update required dependency

---

site/en/tutorials/keras/overfit_and_underfit.ipynb

Proposed change: 
Start by training a model:
or 
Start by training a tiny model:
or 
Start by training a nonlinear model:

elu activation means that it is not a linear model

---

site/en/tutorials/keras/regression.ipynb

Please refer to examples in https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.map.html

Avoid verbose lambda func and use simpler pandas.Series.map

---

site/en/tutorials/keras/classification.ipynb

updated information on overfitting and confidence of the model.
code has been executed successfully in Google Colab.
https://colab.research.google.com/github/cyrus303/docs/blob/docs-update/site/en/tutorials/keras/classification.ipynb

updated document section on the classification.ipynb file in tutorials

---

site/en/guide/keras/custom_callback.ipynb

Very minor edits to custom_callback.ipynb

Fix minor typo in custom_callback.ipynb

---

site/en/guide/upgrade.ipynb

resolves https://github.com/tensorflow/tensorflow/issues/37800

fix a typo in https://www.tensorflow.org/guide/upgrade

---

site/en/tutorials/structured_data/imbalanced_data.ipynb

should be test_predictions_resampled instead of test_predictions_weighted

Correct the second argument of the plot_cm

---

site/en/tutorials/images/data_augmentation.ipynb

[MRG]Correct typo

---

site/en/api_docs/_book.yaml
site/en/api_docs/index.md

Please let me know if there's anything else that needs to be done.

Add link to TensorFlow R language binding

---

site/en/community/forums.md

Hey as the link is broken, in the section "See how to help". And @MarkDaoust  suggested me to delete the sentence. So in this PR, I've deleted that sentence.
fixes: https://github.com/tensorflow/tensorflow/issues/37782

Fixed the broken Link .

---

site/en/tutorials/images/data_augmentation.ipynb

[MRG] Correct typo

---

site/en/guide/saved_model.ipynb
tools/templates/subsite/g3doc/tutorials/notebook.ipynb

refresh, but pretty in sync
```
find . -name "*\.ipynb" | xargs ./tools/nbfmt.py
```

nbfmt: all

---

site/en/guide/data.ipynb
site/en/tutorials/text/transformer.ipynb

Hi,
In loss computation, taking a mean would compute incorrect loss, as mean would divide by number of values in mask. We should divide the total loss by all the non-padded values..

Fix Loss for Tranformer Tutorial

---

site/en/tutorials/keras/text_classification_with_hub.ipynb

As mentioned in the document activation is sigmoid which is mentioned in the layer also

Add activation Fixes #38091

---

site/en/guide/data_performance.ipynb
site/en/guide/keras/functional.ipynb
site/en/guide/keras/masking_and_padding.ipynb
site/en/guide/keras/overview.ipynb
site/en/guide/keras/rnn.ipynb
site/en/guide/upgrade.ipynb
site/en/tutorials/generative/cyclegan.ipynb
site/en/tutorials/load_data/images.ipynb
site/en/tutorials/load_data/tfrecord.ipynb
site/en/tutorials/quickstart/advanced.ipynb
site/en/tutorials/text/text_generation.ipynb
site/en/tutorials/text/word_embeddings.ipynb

```
find . -name "*\.ipynb" | xargs ./tools/nbfmt.py
```

nbfmt sync

---

site/en/r1/guide/extend/architecture.md

Fixed broken links for post training quant and xla

---

site/en/tutorials/estimator/boosted_trees.ipynb

Someone forgot to use the `fc = tf.feature_column` variable that's declared on the feature creation code block, improves readability so I changed the whole rest of the notebook to actually use it.

Estimator Tutorial code readability change

---

site/en/tutorials/quickstart/beginner.ipynb

Simler fix for #38735.
Fixes tensorflow/tesorflow#38735
See also #1548

Or test set.

---

site/en/tutorials/generative/style_transfer.ipynb

"calcualted" to "calculated"
----------
**EDIT:** Also removed an unused variable, `style_result`

Fix minor typo, remove unused variable

---

site/en/install/pip.html

See https://github.com/tensorflow/tensorflow/issues/39768#issuecomment-632894466
This PR should solve similar confusions

Document py3.8 support

---

site/en/tutorials/distribute/multi_worker_with_keras.ipynb

correcting note text to be aligned with the upstream notebook code.
fixes https://github.com/tensorflow/tensorflow/issues/38946

update multi_worker_with_keras nb

---

site/en/install/pip.html
site/en/r1/guide/premade_estimators.md

Change install instructions and mentions of virtualenv to use venv.
@mihaimaruseac

switch to venv for virtual environment

---

site/en/tutorials/structured_data/time_series.ipynb

Hello
I just found a typo during time series tutorial.
> CLA completed

fix: resolve minor typo

---

site/en/tutorials/structured_data/imbalanced_data.ipynb

"These are initial guesses are not great." -> "These initial guesses are not great."

fixed minor grammatical error

---

site/en/install/gpu.md

Update driver version for Ubuntu 18.04 apt install from 430 to 450 to resolve packaging issues reported in [tensorflow issue 40278](https://github.com/tensorflow/tensorflow/issues/40278).
Attention @sanjoy

Update nvidia driver version in gpu install instructions

---

site/en/tutorials/load_data/images.ipynb

Updating load images tutorial. See cl/318698490. Now includes Keras preprocessing utilities.

Updating load_images tutorial

---

site/en/guide/intro_to_graphs.ipynb
site/en/guide/migrate.ipynb
site/en/guide/upgrade.ipynb
site/en/r1/tutorials/eager/automatic_differentiation.ipynb
site/en/r1/tutorials/eager/custom_layers.ipynb
site/en/r1/tutorials/estimators/linear.ipynb
site/en/r1/tutorials/representation/unicode.ipynb
site/en/tutorials/estimator/keras_model_to_estimator.ipynb
site/en/tutorials/generative/cvae.ipynb
site/en/tutorials/generative/cyclegan.ipynb
site/en/tutorials/keras/text_classification.ipynb
site/en/tutorials/load_data/images.ipynb
site/en/tutorials/load_data/tfrecord.ipynb
site/en/tutorials/quickstart/advanced.ipynb
site/en/tutorials/text/text_generation.ipynb
site/en/tutorials/text/word_embeddings.ipynb

Format with the latest `nbfmt`:
```
$ python3 -m pip install -U --user git+https://github.com/tensorflow/docs
$ python3 -m tensorflow_docs.tools.nbfmt .
```

nbfmt all the things

---

site/en/tutorials/keras/classification.ipynb

The "predictions_array" needed to be indexed with [i] for latter use.

Fix errors about index lacking

---

site/en/guide/distributed_training.ipynb
site/en/guide/tpu.ipynb

tf.distribute.experimental.TPUStrategy -> tf.distribute.TPUStrategy

TPUStrategy no longer considered as experimental

---

site/en/tutorials/load_data/tfrecord.ipynb

tf.Example does not exist and is now replaced with tf.train.Example

Replace tf.Example with tf.train.Example

---

site/en/guide/tf_numpy.ipynb

This commit fixes #43089

---

tools/tensorflow_docs/api_generator/generate_lib.py

Fix: https://github.com/tensorflow/tensorflow/issues/43224 /cc @yashk2810

Sort classes with the same order as TOC

---

site/en/tutorials/images/transfer_learning.ipynb

I just removed a two words duplication 👀

Remove duplicate the model in the sentence

---

site/en/tutorials/generative/cyclegan.ipynb

As compared to the [original paper](https://arxiv.org/abs/1703.10593), it seemed that the identity loss defined currently should be changed.

CyclicGAN: corrected identity loss

---

site/en/guide/variable.ipynb

Fix minor typos and style issues in `variable.ipynb`

---

site/en/install/docker.md

The rendering is broken today for the last row on the website.  On github preview the other rows are rendered incorrectly as well.

Clean up the table in docker.md

---

site/en/tutorials/quickstart/advanced.ipynb

f-strings are a more modern alternative to template strings. In this case their primary benefit is in improved readability since they need one less local variable (name), one less function call and thus shorten the code overall. They also increase usability, because they make mixing the replacement strings up much harder.

Use f-strings for formatting

---

site/en/tutorials/structured_data/time_series.ipynb

- The context around the line should show wide_window's shape, not single_step_window's shape

Fix inappropriate variable

---

.github/workflows/ci.yaml

Tested in https://github.com/lamberta/tf-docs/pull/8

Update CI message for notebook outputs

---

site/en/install/gpu.md

Fixes #https://github.com/tensorflow/tensorflow/issues/43933

update gpu software requirements docs

---

site/en/tutorials/keras/classification.ipynb

#1657 
Removed source fork by accident.
Created again please check!

fix: keras to tf.keras for consistency

---

site/en/install/source_windows.md

This fixes a typo. Fixes https://github.com/tensorflow/tensorflow/issues/44051

Update CuDNN version for CUDA 10.1 versions

---

site/en/tutorials/load_data/csv.ipynb

Easy navigation and easy reading.

Fix broken url in docs

---

site/en/tutorials/images/classification.ipynb
site/en/tutorials/load_data/text.ipynb

Fix linter warnings in Image classification notebook

---

site/en/guide/basic_training_loops.ipynb

Fix link to tutorial

---

site/en/guide/data.ipynb
site/en/r1/tutorials/estimators/linear.ipynb
site/en/tutorials/audio/simple_audio.ipynb
site/en/tutorials/load_data/csv.ipynb

Remove default value parameters:
- `index_col=None` by default
- `header=None` by default when `names` are passed

Remove redundant pandas default value parameters

---

site/en/tutorials/structured_data/imbalanced_data.ipynb

I fixed unnatural spaces in tutorials/structured_data/imbalanced_data.ipynb.

Fix spaces in tutorials/structured_data/imbalanced_data.ipynb

---

site/en/install/gpu.md

Updated the older link  with newer link for the installation of Ubuntu 16.04 (CUDA 10.1).

Updated the older link to Ubuntu 16.04 (CUDA 10.1)

---

site/en/install/gpu.md
site/en/install/pip.html

Removed the NVIDIA driver installation step as it is installed by default in next step.
fixes issue number #44301
Made changes as suggested in [#40959](https://github.com/tensorflow/tensorflow/issues/40959#issuecomment-656397448).

Updated gpu.md and pip.html

---

site/en/guide/autodiff.ipynb

Splitting PR https://github.com/tensorflow/docs/pull/1736 into smaller digestible bits. Thank you @lamberta @MarkDaoust

Lint TensorFlow: Intro to gradients and automatic differentiation

---

site/en/guide/estimator.ipynb

Splitting PR https://github.com/tensorflow/docs/pull/1736 into smaller digestible bits. Thank you @lamberta @MarkDaoust

Lint TensorFlow Estimators guide

---

site/en/tutorials/keras/overfit_and_underfit.ipynb

Fix broken sentence made in 2ae72fcf5b4cef24fbace092fcba69ee6a849cac

Fix broken  sentence

---

site/en/guide/autodiff.ipynb

try to fix the possible problematic example reported in https://github.com/tensorflow/tensorflow/issues/45181

fix example code

---

site/en/tutorials/generative/autoencoder.ipynb

recontruction -> reconstruction

corrected a spelling mistake

---

site/en/tutorials/keras/text_classification.ipynb

Correct a spelling mistake

---

site/en/guide/data.ipynb

Fixes: tensorflow/tensorflow#44779

Fix #44779 : data.ipynb file updated

---

site/en/tutorials/text/text_classification_rnn.ipynb

fixed typos : reasns -> reasons and neew -> new

fixed typos : reasns -> reasons and neew -> new

---

site/en/guide/keras/README.md

Fixed broken link to keras guide

---

site/en/guide/data_performance.ipynb

Hello,
For the "__new__" function I received the following warning:
```
WARNING:tensorflow:From <ipython-input-3-2d96a5e17d28>:17: calling DatasetV2.from_generator (from tensorflow.python.data.ops.dataset_ops) with output_types is deprecated and will be removed in a future version.
Instructions for updating:
Use output_signature instead
WARNING:tensorflow:From <ipython-input-3-2d96a5e17d28>:17: calling DatasetV2.from_generator (from tensorflow.python.data.ops.dataset_ops) with output_shapes is deprecated and will be removed in a future version.
Instructions for updating:
Use output_signature instead
```
So I went through the official documentation, and then updated the lines accordingly. The code now runs without the warning.
Best Regards,
Matthew Tafazoli

Edit __new__ to not return Warning

---

site/en/guide/autodiff.ipynb
site/en/tutorials/distribute/multi_worker_with_keras.ipynb
site/en/tutorials/distribute/parameter_server_training.ipynb
site/en/tutorials/images/data_augmentation.ipynb
site/en/tutorials/images/transfer_learning_with_hub.ipynb
site/en/tutorials/keras/text_classification_with_hub.ipynb
site/en/tutorials/text/classify_text_with_bert.ipynb
site/en/tutorials/text/solve_glue_tasks_using_bert_on_tpu.ipynb
site/en/tutorials/text/word2vec.ipynb
site/en/tutorials/text/word_embeddings.ipynb

Correct from dy = 2x * dx to dys/dx1 = exp(x1) / (1 + exp(x1)).

Correct derivative

---

site/en/install/pip.html

broken link to The latest supported Visual C++ downloads

fix broken link in update pip.html

---

.github/workflows/bot-nightly.yaml

Also: use python 3.8 and format the python source files

keras guides sync: Do not keep rest of branch updated

---

site/en/tutorials/generative/cvae.ipynb

Corrected a grammatical mistake in sentence 2.

Updated cvae.ipynb

---

site/en/tutorials/keras/text_classification_with_hub.ipynb

Following this tutorial locally causes: `ModuleNotFoundError: No module named 'tensorflow_datasets'`

pip install tensorflow-datasets - required for tensorflow_datasets module used in tutorial

---

site/en/community/contribute/code.md

... to make it easier for people to find the right information

add links to contributor checklist

---

site/en/tutorials/keras/keras_tuner.ipynb

Resolves: https://github.com/tensorflow/tensorflow/issues/47725

Keras Tuner - Fix model retrain parameters

---

site/en/tutorials/keras/save_and_load.ipynb

I was referring back to the [Save and load models](https://www.tensorflow.org/tutorials/keras/save_and_load) tutorials running this notebook on my personal Windows machine and I noticed it using POSIX commands which give an error on Windows machines. An easy fix can be made to solve this using `os` commands instead.
I also found an associated issue with it https://github.com/tensorflow/tensorflow/issues/33923 , which should be closed by this PR.
cc: @MarkDaoust

Update Save and Load models to be platform independent

---

site/en/tutorials/load_data/text.ipynb
site/en/tutorials/text/word2vec.ipynb

In this PR I have rectified the mapping function.
Previously the `text_ds` was mapped to the `vectorize_layer` which is a `TextVectorization` layer. Now it correctly maps to the `vectorixe_text` method that is written in the code cell itself.

Map the text dataset to the proper function.

---

site/en/tutorials/keras/regression.ipynb

They are functions of each other.

chore: sentence grammar small fix

---

site/en/community/contribute/community.md

We could move or refactoring that later

Add a reference to our Governance

---

CODEOWNERS

Had gotten pretty stale: adding in more current owners

Update community owners for docs

---

site/en/tutorials/load_data/images.ipynb

Removes repeated words "to the"

Fix grammatic error in site/en/tutorials/load_data/images.ipynb

---

site/en/tutorials/structured_data/imbalanced_data.ipynb

As mentioned in the title, solved https://github.com/tensorflow/tensorflow/issues/45615

Add Precision-recall curve in the imbalanced data tutorial #45615

---

site/en/tutorials/text/word2vec.ipynb

Existing code did not load the TensorBoard notebook extension before using the embedded TensorBoard viewer in `site/en/tutorials/text/word2vec.ipynb`

Added The Missing Code in word2vec.ipynb

---

site/en/tutorials/text/classify_text_with_bert.ipynb

@lamberta @MarkDaoust Very small changes (commas and spelling, such as "optimizer", "URL", "yield"). It's a nice tutorial about using a pre-trained Transformer for NLP, it's very hot these days.

Nit: Lint the Classify text with BERT tutorial

---

site/en/tensorboard/README.md

Add Tensorboard and remove Tensorflow Probability in README.md

Add Tensorboard and remove Tensorflow Probability in README

---

site/en/tutorials/structured_data/imbalanced_data.ipynb

change unnatural formula a little

fix formula

---

site/en/guide/tpu.ipynb

Change the `experimental_steps_per_execution` to `steps_per_execution` in TPU Guide

`steps_per_execution` is no more experimental

---

site/en/tutorials/keras/keras_tuner.ipynb

It should be `keras_tuner`, not `kerastuner`

Fix import

---

site/en/tutorials/load_data/text.ipynb

The validation dataset is the same as training dataset.
This is fixed by taking 80% of train for training and 20% for
validation.

Fix validation dataset

---

site/en/tutorials/structured_data/time_series.ipynb

_Thank you for this wonderful and detailed tutorial. Learnt so much!_
- Ref: https://www.tensorflow.org/tutorials/structured_data/time_series

Modify label to Label in the print statement

---

site/en/guide/gpu.ipynb

changed from tf.config.experimental.set_visible_devices to tf.config.set_visible_devices.
changed from tf.config.experimental.set_virtual_device_configuration to tf.config.set_logical_device_configuration

updated experimental details

---

site/en/tutorials/keras/regression.ipynb

Updated broken link for  this "represents a sequence of steps" from .././guide/keras/sequential_model.ipynb to https://www.tensorflow.org/guide/keras/sequential_model.

Updated broken link

---

tools/tensorflow_docs/tools/README.md

Adding $ to keep consistency of differentiating command-line snippets from code snippets.

Adding $ to show it is a command-line snippet

---

site/en/tutorials/text/word2vec.ipynb

Fix grammar typo

---

site/en/tutorials/keras/classification.ipynb

Properly formatted the logits definition.
Fixes https://github.com/tensorflow/tensorflow/issues/47553

Updated logits.

---

site/en/install/gpu.md

Adding instructions for WSL2 on Windows.

Instructions for WSL2

---

site/en/install/_index.yaml

Adding experimental support for WSL2 on MS Windows.

Adding experimental support for WSL2 on MS Windows

---

site/en/guide/saved_model.ipynb

updated broken link of tf.function guide .

updated broken link of tf.function

---

site/en/tutorials/keras/text_classification.ipynb

Fixed Broken link for  word_embedding notebook

Fixed Broken link for  word_embedding

---

site/en/community/contribute/community.md

Will add link to SIG lists once new page is created

Update “Contribute to the community” on TensorFlow.org

---

site/en/guide/migrate/upgrade.ipynb

Updated tf2up.ml with Github link as per author's request.

Fixes broken link issue in #54660

---

site/en/guide/checkpoint.ipynb

Fixed Broken link on "Saving and Restoring" with website link.

Fixed Broken link on "Saving and Restoring"

---

site/en/tutorials/customization/basics.ipynb

Correct language issues in the tensors and operations page:
"This enables a more interactive frontend to TensorFlow, the details of which we will discuss much later."
1. "This" should not be used without an object for clarity: "This enables" --> "This xxxx enables"
2. Use second person ("you") instead of "we"
https://developers.google.com/style/person?hl=en
3. Inclusive language: native -> built-in
Existing URLs containing the issue:
https://www.tensorflow.org/tutorials/customization/basics

sentence structure and inclusive language:  basics.ipynb

---

site/en/tutorials/structured_data/imbalanced_data.ipynb

The AUPRC plot takes precision for x-axis and recall for y-axis.

Correct plot labels of AUPRC

---

site/en/install/source.md

The Bazel docs have moved and the links in this document should be updated.

Update bazel reference links

---

site/en/guide/graph_optimization.ipynb

Removed a link that was broken

Remove Broken link

---

site/en/guide/function.ipynb

Fixed broken link with correct link

Fixing Broken Link

---

site/en/guide/distributed_training.ipynb
site/en/guide/saved_model.ipynb
site/en/tutorials/load_data/images.ipynb

Update alias to standard name.
From `tf.losses.SparseCategoricalCrossentropy` to `tf.keras.losses.SparseCategoricalCrossentropy`

Update `tf.losses` and `tf.optimizers` to Keras

---

site/en/guide/extension_type.ipynb

Update Broken References:
1.  Change from `tf.experimental.dispatch_for_unary_elementwise_api` to `tf.experimental.dispatch_for_unary_elementwise_apis`
2.  Change from `tf.Keras` to `tf.keras`

Update Broken References

---

site/en/tutorials/keras/text_classification.ipynb

Add an instruction to add a Softmax layer. Otherwise the accuracy would be around 0.3, not far away from the random-guess 0.25.

tutorials/keras/text_classification.ipynb: Refine exercise instruction

---

site/en/guide/function.ipynb

tried on colab,
some of the features run only on tensorflow >= 2.9.1 
you might need to install the nightly built version in order to try this tutorial.

Update TF version required for the tf.function guide

---

site/en/tutorials/generative/pix2pix.ipynb

Changed the link in the line 81

Lint links in conditional GAN pix2pix tutorial

---

site/en/install/pip.md

Fix broken style on https://www.tensorflow.org/install/pip#step-by-step_instructions

Fix installation guide broken style

---

site/en/tutorials/load_data/video.ipynb

Remove variables that are declared but not used

Load video code fixes

---

site/en/install/source.md

Updated session details with new console output . Fixes #[32085](https://github.com/tensorflow/tensorflow/issues/32085)

Updated session details with new console output

---

site/en/guide/core/optimizers_core.ipynb

In the gradient descent with momentum formula, I think the gradient function $L^\\prime$ should use $x^{[t-1]}$ to cumpute the new delta.
$$
\\Delta_x^{[t]} = lr \\cdot L^\\prime(x^{[t-1]}) + p \\cdot \\Delta_x^{[t-1]}
$$

formula fix

---

site/en/tutorials/load_data/csv.ipynb

Updated load data docs with new api.
Replaced old depreciated api
tf.data.experimental.snapshot 
with new api
tf.data.Dataset.snapshot

Updated load_data docs with new api

---

site/en/install/errors.md

Fixed tag sequence issue in errors.md which might create problem while rendering the page in some devices.

Fixed tag sequence issue in errors.md

---

.github/workflows/bot-pr-new.yaml

Use sha instead of ref

---

site/en/guide/create_op.md

Updated the link for relu_op_test.py, TensorFlow binary & downloaded TensorFlow source

Updated the links in create_op.md

---

site/en/guide/basics.ipynb

https://www.tensorflow.org/guide/basics

Fixes typo error

---

site/en/guide/versions.md

Fixed the broken link for Python in line 37

Fixed the broken link in versions.md

---

site/en/guide/basics.ipynb
site/en/guide/core/distribution.ipynb
site/en/guide/core/matrix_core.ipynb
site/en/guide/core/mlp_core.ipynb
site/en/guide/core/quickstart_core.ipynb
site/en/guide/data_performance.ipynb
site/en/guide/estimator.ipynb
site/en/guide/function.ipynb
site/en/guide/intro_to_graphs.ipynb
site/en/guide/intro_to_modules.ipynb
site/en/guide/jax2tf.ipynb
site/en/guide/migrate/evaluator.ipynb
site/en/guide/migrate/multi_worker_cpu_gpu_training.ipynb
site/en/guide/migrate/saved_model.ipynb
site/en/guide/migrate/tensorboard.ipynb
site/en/guide/migrate/tpu_embedding.ipynb
site/en/guide/saved_model.ipynb
site/en/guide/tensor.ipynb
site/en/guide/tensor_slicing.ipynb

In https://github.com/tensorflow/docs/pull/2232, the nbfmt check was failing, so I've run it over all guides.

Run `nbfmt` on guide notebooks

---

site/en/guide/core/logistic_regression_core.ipynb

`confusion_normalized`'s rows should add up to 1.

Fixed confusion matrix normalization issue.

---

site/en/install/pip.md

As tensorflow 2.13v is rolled out and wheels are also updated but still `pip.md` file have `pip install tensorflow==2.12.* `command which i want to update to `pip install tensorflow==2.13.*`
Thanks!

Update tf version to 2.13. from 2.12 in pip install command in pip.md

---

site/en/tutorials/interpretability/integrated_gradients.ipynb

Documentation changes Integrated_gradients.ipynb

Documentation changes to enhance readability

---

site/en/guide/tensor.ipynb

The function should be `tf.strings.to_number`

Fix a typo: tf.strings.to_number

---

site/en/guide/intro_to_graphs.ipynb

removed bracket in polymorphism section for id() builtin link

corrected typo in intro to graphs guide section

---

tools/tensorflow_docs/api_generator/parser.py

@MarkDaoust @markmcd @mihaimaruseac

Update parser.py, add URL substring sanitization

---

.github/workflows/stale.yaml

As it is written it will only affect issues labeled "awaiting contributor response"

Add a workflow for stale issues/PRs

---

site/en/community/contribute/code.md

`Thank you for work and interest` => `Thank you for your work and interest`

Improve the grammar

---

site/en/tutorials/distribute/dtensor_ml_tutorial.ipynb

Fix DTensor concepts link

---

tools/tensorflow_docs/api_generator/doc_generator_visitor.py

fix typo error "decsription" -> "description"

fix typo error "description"
