site/en/install/install_linux.md

Updated install guide to indicate cuDNN 7.2 is needed.  This does not need to wait until 1.11 is final as moving to cuDNN 7.2 works just fine with current 1.10 binaries.  The move is needed because the latest TensorRT requires cuDNN 7.2.

cuDNN 7.2 required for tf 1.11+

---

site/en/tutorials/eager/automatic_differentiation.ipynb
site/en/tutorials/eager/custom_layers.ipynb
site/en/tutorials/eager/custom_training.ipynb
site/en/tutorials/eager/custom_training_walkthrough.ipynb
site/en/tutorials/eager/eager_basics.ipynb

The links to Colab and GitHub source in the eager tutorial nootebooks are outdated.
These notebooks are moved to tensorflow/docs repository.
I updated the links in this pull req.
I have signed CLA to submit pull request to tensorflow/tensorflow repository before. Is that cover submitting a patch to tensorflow/docs too?

Update links in eager tutorials for docs repo.

---

site/en/community/style_guide.md

Porting noted TF styles here:
https://github.com/tensorflow/probability/blob/master/STYLE_GUIDE.md

Move noted TF styles from TFP to official TF style guide.

---

site/en/guide/autograph.ipynb

This moved out of contrib.
Fixes https://github.com/tensorflow/tensorflow/issues/22280

Rename contrib autograph links

---

site/en/guide/keras.md

Keras custom layers example code missed a return statement, which
caused layers to not have a config when the example was followed.

Add missing return in example code

---

site/en/guide/datasets.md

Error:
TypeError: Value passed to parameter 'dense_defaults' has DataType int32 not in list of allowed values: float32, int64, string

TF doc: guide/datasets: int32 is not supported in Example proto.

---

site/en/install/docker.md
site/en/install/pip.html

Using `pip install --user virtualenv` presents some complications since the installation `bin/` usually this *isn't* on the user's `PATH`.
Could add something like:
`PATH="$(python -m site --user-base)/bin:$PATH"`
And then another for python3. Not sure if this works for Windows, etc.
Since we're already using `sudo` to use the system package manager, I think—in this case—it's easier for beginners to just to install `virtualenv` system-wide. (This change is based on feedback from a new user.)
stage: go/tfo-stage/install/pip

Use sudo for installing virtualenv

---

site/en/install/_toc.yaml

Causing lower tabs to not show up on /lite

remove link to lite subsite from install toc

---

site/en/deploy/hadoop.md

* Removed an unrelated reference to HADOOP-10903. The issue describes the addition of the --glob flag to the `hadoop` command. It does not give any context on why this is necessary. In fact, I've failed to find any reference explaining this behaviour other than this SO answer: https://stackoverflow.com/a/9322747/262432.
* ${} are now used consistently in Bash snippets.

Cleanup on the Hadoop page

---

site/en/api_docs/_book.yaml

Some redirects here: cl/214344585
Not many, though, and I'm not sure there's much here worth saving.

Remove API Guides from api_docs/ leftnav

---

site/en/install/pip.html

Tensorflow only supports 64-bit versions of Python 3.5.x and 3.6.x on Windows.
It was mentioned on previous install guides.

Mention 64-bit python need on windows

---

site/en/extend/adding_an_op.md

I was also bit by tensorflow/tensorflow#9137 and tensorflow/tensorflow#10714.  Even though the necessary bazel option is technically in the docs I missed it because it was mentioned in the system compiler section, not the bazel build section.  Since I never planned to use my system compiler I skipped that section and went straight to bazel build.  For maximum clarity it would be nice to co-locate the bazel option next to the bazel build command.

Move bazel gcc>=5 abi option from system compiler to bazel build section

---

site/en/about/uses.md

The previous uses.md file made use of the unordered list and list items tags of html which caused the bold markdown to not render. replaced the &lt;ul&gt; and &lt;li&gt; tags with markdown equivalents.

updates markdown in uses file under about

---

site/en/api_guides/python/reading_data.md
site/en/api_guides/python/regression_examples.md

As part of our sample modernization, we are removing references to outdated samples until such time as they can be cleaned up.  These are two that need updating.

Removing some outdated sample references from guides

---

site/en/extend/xla/README.md

Missed this one. XLA is under /extend now

Move xla warp zone readme

---

site/en/tutorials/images/deep_cnn.md

Also:
- remove a few references to obsolete queue API
- add hints on how to start tensorboard so reader doesn't have to search for default {eval,train}_dir flags.

Update tutorial to use tensorflow/datasets library.

---

site/en/tutorials/sequences/text_generation.ipynb

Chunks were not defined in the updated version. Sequences should have been used instead.

fix small typo

---

site/en/guide/saved_model.md

The option `--inputs` of `saved_model_cli` needs a single quote when multiple inputs are specified.
This patch fixes it.

Fix: example of saved_model_cli with multiple inputs

---

site/en/tutorials/keras/save_and_restore_models.ipynb

This is still in contrib, but there's no other other similarly easy way to get a saved model out, so I think it's worth including. I've included a "Caution: this is experimental" above.
Staging: https://colab.sandbox.google.com/github/MarkDaoust/docs/blob/saved-model/site/en/tutorials/keras/save_and_restore_models.ipynb

Add a section on saved_model

---

site/en/tutorials/eager/automatic_differentiation.ipynb
site/en/tutorials/eager/custom_layers.ipynb

Specifically, this PR removes the gradients_function section from the eager/automatic_differentiation tutorial, and removes an unused `tfe = tf.contrib.eager` call from the eager/custom_layers tutorial.
Staging:
https://colab.sandbox.google.com/github/tomerk/docs/blob/remove-eager-contrib/site/en/tutorials/eager/automatic_differentiation.ipynb
https://colab.sandbox.google.com/github/tomerk/docs/blob/remove-eager-contrib/site/en/tutorials/eager/custom_layers.ipynb

Removes eager contrib from some eager tutorials

---

site/en/guide/extend/bindings.md
site/en/guide/extend/filesystem.md
site/en/guide/extend/formats.md
site/en/guide/faq.md
site/en/tutorials/representation/word2vec.md

Some links were pointing to https://www.tensorflow.org/guide/extend/adding_an_op

Fix `Adding an op` links in the doc

---

site/en/tutorials/keras/save_and_restore_models.ipynb

Note: this is slightly suboptimal for tf v1 until we activate the v2 keras optimizers even in tf v1. Until then this warning gets printed:
```
logging.warning(
('This model was compiled with a Keras optimizer (%s) but is being '
'saved in TensorFlow format with `save_weights`. The model\'s '
'weights will be saved, but unlike with TensorFlow optimizers in '
'the TensorFlow format the optimizer\'s state will not be '
'saved.\n\nConsider using a TensorFlow optimizer from `tf.train`.')
% (optimizer,))
```

Switched to use Keras optimizers in save_and_restore for tf v2 compatibility

---

site/en/guide/low_level_intro.md

The current instructions create a writer and add a graph but do not output the graph to a file. Adding the writer.flush() command will write the graph to a file.

Update the TensorBoard section to write the graph to a file.

---

site/en/tutorials/keras/basic_text_classification.ipynb

This particular `[3, 5]` sequence is used to explain multi-hot encoding in overfit_and_underfit notebook.
To prevent confusing, I want to change one-hot-encode to multi-hot-encode in basic_text_classification notebook.
Thanks. :)

change one-hot to multi-hot for consistency with overfit_and_underfit

---

site/en/guide/graphs.md

In-doc links now working: use` -` for word separation

markdown fix

---

site/en/tutorials/keras/basic_classification.ipynb

Issues fixed in this PR:
1. Casting is not done and there is no need to be done ==> removed redundant sentence.
2. There is no preprocessing function defined ==> removed redundant sentence.

Fix basic classification tutorial

---

site/en/guide/keras.ipynb

Curious if we need {:.external} in the notebooks?
Reasoning: on tensorflow.org it renders as an external link symbol, but in the text it looks a bit messy.
Met those while doing keras translation.

Does {:.external} class in ipynb neccessary?

---

site/en/tutorials/keras/overfit_and_underfit.ipynb

It is often used interchangeable, but actually L2 regularization is squared l2 norm, not l2 norm.
To avoid misunderstanding, adding 'squared' is recommended.

Add 'squared' to L2 regularization description

---

site/en/guide/keras.ipynb

Name of the chapter and its sections should be in separated markdown cells in order to render each section in the table of contents in Colab.
Not necessarily a bug, but something to remember.

colab: rendering all sections in the table of contents

---

site/en/guide/tensors.md

Not sure about this as I stumbled upon the line while translating:
Would it be better to refer to a `string` as an `object` when there's only one item, e.g. not a `list` with several `items`?
If not just reject the PR, I might be sleepy :)

Renaming item->object

---

site/en/tutorials/images/image_recognition.md

Due to updates in the GitHub markdown processor, the markdown for H2 headings is only rendered when there is space between `##` and the `title`. I have updated the markdown with space so that the header is rendered properly.
Previously:
Current:

Fix heading issue in markdown

---

site/en/tutorials/load_data/images.ipynb

It still needs an introduction and conclusion paragraph.
But this won't be visible on the site unless we add it to the "_toc.yaml"
Staging:
https://github.com/MarkDaoust/docs/blob/load_data/site/en/tutorials/load_data/images.ipynb
https://colab.sandbox.google.com/github/MarkDaoust/docs/blob/load_data/site/en/tutorials/load_data/images.ipynb

A first draft of "loading data: images"

---

site/en/tutorials/keras/basic_text_classification.ipynb

1. _history_dict_ variable was already declared, so there is no reason to use _history.history_ again.
2. _acc_values_ and _val_acc_values_ are not used because they are equal to _acc_ and _val_acc_.

Remove unnecessary variables in text classification tutorial

---

site/en/tutorials/keras/basic_classification.ipynb
site/ko/tutorials/keras/basic_classification.ipynb
site/ru/tutorials/keras/basic_classification.ipynb

When I was working though the tutorial:
https://www.tensorflow.org/tutorials/keras/basic_classification
the plot window did not appear for me.
Having not used matplotlib before, I spent quite a while trying to set up different configurations before discovering that the example simply needed to call plt.show()

Add plt.show() to basic classification tuturial so something appears.

---

site/en/tutorials/load_data/tf_records.ipynb

Printing the wrong variable after parsing a tf_record with the feature specs. This results in a raw tensor being printed multiple times instead of dicts of features as intended.
Currently printing
```shell
<tf.Tensor: id=61, shape=(), dtype=string, numpy=b'\nR\n\x11\n\x08feature0\x12\x05\x1a\x03\n\x01\x01\n\x11\n\x08feature1\x12\x05\x1a\x03\n\x01\x04\n\x14\n\x08feature2\x12\x08\n\x06\n\x04goat\n\x14\n\x08feature3\x12\x08\x12\x06\n\x04\x943\xe8\xbe'>
<tf.Tensor: id=61, shape=(), dtype=string, numpy=b'\nR\n\x11\n\x08feature0\x12\x05\x1a\x03\n\x01\x01\n\x11\n\x08feature1\x12\x05\x1a\x03\n\x01\x04\n\x14\n\x08feature2\x12\x08\n\x06\n\x04goat\n\x14\n\x08feature3\x12\x08\x12\x06\n\x04\x943\xe8\xbe'>
<tf.Tensor: id=61, shape=(), dtype=string, …
```

Fix typo in tf_records parsing example

---

site/en/tutorials/sequences/recurrent_quickdraw.md

When computing deltas the previous code was skipping the last column and hence reducing the size to [number of points , 2] instead of [number of points, 3].
Just copied the correct code from quickdraw/train_model.py

Fixed bug in the parse_line function example

---

.gitattributes

The motivation was  [PR337](https://github.com/tensorflow/docs/pull/337), because it change end of file.

force eol for .ipynb

---

site/en/install/gpu.md
site/en/install/source.md

Should not be merged until 1.13.0 is RC at a minimum (so likely after the holiday). I do reference CUDA 10 being for >= 1.13.0 in the instructions but it is confusing. :-(

CUDA 10 install instructions.

---

site/ko/r2/tutorials/keras/basic_classification.ipynb
site/ko/r2/tutorials/keras/basic_regression.ipynb
site/ko/r2/tutorials/keras/basic_text_classification.ipynb
site/ko/r2/tutorials/keras/overfit_and_underfit.ipynb
site/ko/r2/tutorials/keras/save_and_restore_models.ipynb

Change `tensorflow.org/tutorials/` to `tensorflow.org/alpha/tutorials/`
Thanks.

Update for tensorflow.org/alpha link

---

site/en/install/source.md

adding `setuptools` to `pip install` instruction otherwise building the wheel package would fail with:
```
$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Sun Mar 3 22:24:31 CET 2019 : === Preparing sources in dir: /tmp/tmp.lOEexzCqAk
~/proj/local/tensorflow ~/proj/local/tensorflow
~/proj/local/tensorflow
Sun Mar 3 22:24:36 CET 2019 : === Building wheel
Traceback (most recent call last):
File "setup.py", line 37, in <module>
from setuptools import Command
ModuleNotFoundError: No module named 'setuptools'
```

pip install setuptools is needed when building from source

---

site/en/install/_index.yaml
site/en/tutorials/_index.yaml

This appears on the following live links:
- <https://www.tensorflow.org/install>
- <https://www.tensorflow.org/tutorials>

typo: “is [a] lightweight solution”

---

site/en/tutorials/images/transfer_learning.ipynb

Fix typo (orginial -> original) in the [tutorial for transfer learning](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/images/transfer_learning.ipynb)

Fix typo in transfer_learning.ipynb

---

site/pt/README.md
site/pt/tutorials/keras/basic_classification.ipynb

Added note to README and notebook.
stage: https://colab.research.google.com/github/lamberta/tf-docs/blob/pt-note/site/pt/tutorials/keras/basic_classification.ipynb
Continued from https://github.com/tensorflow/docs/pull/392

Add community translation note/readme for Portuguese

---

site/en/tutorials/images/_image_classification.ipynb

Before the file went from "en/images" but there is a tutorials folder in the middle so I added "en/tutorials/images" The Tensorflow link is still broken.

Fixed Colab and Github link

---

site/en/install/pip.html

Reference to #26937.
Changed to `tensorflow-gpu==2.0.0-alpha0` rather than `tensorflow==2.0.0-alpha0-gpu`.

Updated install documentation for TF 2.0.

---

site/en/tutorials/estimators/linear.ipynb

Previous code printed evaluation result of model built couple cells before the one evaluated in this cell (note different variable names: `results` and `result` without `s` at the end; `results` is the one that was meant to be printed).
This change fixes that and updates comment that comes after to reflect actual (rounded) accuracy of this model

Fix typo in estimators/linear.ipynb tutorial code

---

site/en/guide/keras.ipynb

The original notebook uses `np.random.random((1000, 10))` to generate the label for a classification model. This is incorrect as the correct target label should be one-hot-encoded. This commit fixes this problem.

Correctly use one-hot-encoded matrices as label

---

site/en/install/gpu.md

Add instructions to include the 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include' directory to the PATH variable. This ommission has been the cause of confusion and frustration for multiple Windows users. Myself included.

Add missing Install Instructions

---

site/en/r2/tutorials/estimators/boosted_trees.ipynb
site/en/r2/tutorials/images/intro_to_cnns.ipynb
site/en/tutorials/estimators/boosted_trees.ipynb
site/en/tutorials/estimators/boosted_trees_model_understanding.ipynb
tools/templates/notebook.ipynb

1. Set Colab url in intro_to_cnns.ipynb (It was set to github url).
2. Change colab.sandbox.google.com to colab.research.google.com in colab urls.

Fix colab urls

---

site/en/r2/tutorials/images/transfer_learning.ipynb

Notebook : Transfer Learning Using Pretrained ConvNets
Heading : Add a classification head
`tf.keras.layers.GlobalAveragePlloing2d `-> `tf.keras.layers.GlobalAveragePooling2D`

Fixed typo in Tensorflow alpha docs

---

site/en/tutorials/load_data/tf_records.ipynb

This PR fixes a couple of open ends on the TF Records tutorial [page/notebook](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/load_data/tf_records.ipynb).
- Fixes typos in two cells. 
- Changed the python wrapper function from `py_func` to the new `py_function` as `py_func` is deprecated and will be removed soon. Updated related functions to match return types where necessary.

TFRecords tutorial: Switch to `py_function` and typo fixes.

---

site/en/r2/guide/effective_tf2.md

In codes to obtain gradients using `GraidentTape`, `tape.gradients` should be `tape.gradient`

Fix typo in Effective_TF2.md

---

site/en/tutorials/images/hub_with_keras.ipynb

enable_v2_behavior is not available in the latest builds.
Calling it produces:
AttributeError: module 'tensorflow' has no attribute 'enable_v2_behavior'

enable v2 behavior is not available

---

site/en/r2/tutorials/text/word_embeddings.ipynb

this may lead to think that in the integer encoding different words can have similar number to represent them.

removing doubt in the sentence

---

site/en/guide/embedding.md

Changed the file as guided in #473 
@lamberta now please look into this !

Updated embedding.md

---

site/en/install/gpu.md

The Ubuntu 16.04 (CUDA 9.0 for TensorFlow < 1.13.0) install instructions did not include commands for installing an Nvidia driver

Added commands to install Nvidia driver for CUDA 9

---

site/en/r2/tutorials/generative/style_transfer.ipynb

Replacing `decode_jpeg` by the generic `decode_image` and setting up `channels=3` allows the use of this util function to work with PNG images, which come with 4 channels.

Enable use of PNG input images.

---

tools/tensorflow_docs/api_generator/parser.py

In Python 3.7 recommendation from PEP 479 was enabled. In the new
behavior StopIteration exceptions raised directly or indirectly in coroutines
and generators are transformed into RuntimeError exceptions.
https://www.python.org/dev/peps/pep-0479/

Fix api_generator.parser._gen_pairs to work in Python 3.7

---

site/en/guide/using_gpu.md
site/en/r2/guide/using_gpu.md

As mentioned in [this comment](https://github.com/tensorflow/tensorflow/commit/5d2047029a77545c97c0fdf74d9c03c92d1dcb88#commitcomment-33445269) to the commit of discussed functionality, I'd like to have it mentioned here, as it is the most relevant place for it to be mentioned that I could find.
Since I failed to find info about whether this feature is intended to be kept around and integrated into TF2 in the future development, or its future is not that certain, I'd like to at least start the discussion through this PR and maybe advocate for it, as I recently found it most useful and would really appreciate for it to be standardized/propagated into future TF2 stable releases.
Thanks for any reply!

Mention TF_FORCE_GPU_ALLOW_GROWTH in using_gpu.md

---

site/ja/js/tutorials/learning/ml.md

I translated below into Japanese.
https://github.com/tensorflow/tfjs-website/blob/devsite/docs/tutorials/learning/ml.md

JA: add js/tutorials/learning/ml.md

---

site/ja/js/tutorials/setup.md

I translated below into Japanese.
https://github.com/tensorflow/tfjs-website/blob/devsite/docs/tutorials/setup.md

JA: add js/tutorials/setup.md

---

site/en/r2/guide/keras/training_and_evaluation.ipynb

Fix a typo in section "Using the TensorBoard callback".

Fix a typo in training_and_evaluation.ipynb

---

site/en/r2/tutorials/images/_image_classification.ipynb

I found typo and fix it when I translate this document to Japanese.

Fix typo in _image_classification.ipynb

---

site/en/r2/tutorials/keras/basic_text_classification_with_tfhub.ipynb

* two --> three
* anout --> about
* 40 --> 20 (Acutally the model start overfitting in 20th epoch)
Thanks!

Fix typos in basic_text_classification_with_tfhub.ipynb

---

site/en/r2/tutorials/generative/dcgan.ipynb
site/en/r2/tutorials/keras/overfit_and_underfit.ipynb
site/en/tutorials/keras/overfit_and_underfit.ipynb

minor typo fixes

---

site/en/r2/guide/keras/overview.ipynb

`dataset.md` link is not working in the current page as reported in this [issue](https://github.com/tensorflow/tensorflow/issues/29047)

updated link to dataset

---

site/en/r2/tutorials/load_data/tf_records.ipynb

Fix to [29352](https://github.com/tensorflow/tensorflow/issues/29352).
Seems like in TF version 2 the link is not clickable.

broken link fix

---

tools/tensorflow_docs/api_generator/parser.py

This is a fix to [29339](https://github.com/tensorflow/tensorflow/issues/29339).
My tests are highlighted in the following screenshot:

edited regex to ignore code comments in auto-linking

---

site/en/r2/tutorials/text/transformer.ipynb

`output = tf.matmul(attention_weights, v)  # (..., seq_len_v, depth_v)`
should be 
output = tf.matmul(attention_weights, v)  # (..., seq_len_q, depth_v)

Minor correction

---

site/en/guide/using_tpu.md

Just a minor correction to variable names used in the example code for TPU setup.  A couple of the variables used are undefined (but clearly intended to refer to similarly-named previous variables).

Fix undefined variable names in using_tpu docs.

---

site/en/install/gpu.md

fix wrong version numbers - libcudnn is still working with old numbers but libnvinfer5 is not
you can also use `7.6.0.64-1+cuda10.0` for `libcudnn7` but it auto upgraded to `7.6.0.64-1+cuda10.1` - so who cares and libnvinfer5 will only install with `libnvinfer5=5.1.5-1+cuda10.0` or `libnvinfer5=5.1.2-1+cuda10.0` if you pass it the correct version number. Same for the development library. Just signed the CLA
Would be nice if I knew this earlier (using a Ubuntu  / kubuntu 19.04 disco base system with repos for LTS 18.04.2)

NVIDIA updated their machine learning repos

---

site/en/r2/tutorials/generative/style_transfer.ipynb

The variable 'steps' should be called 'steps_per_epoch'. Probably overlooked when running the notebook since 'steps_per_epoch' had been defined before.

Rename variable 'steps' to 'steps_per_epoch'

---

site/en/tutorials/_toc.yaml
site/en/tutorials/images/transfer_learning.ipynb

This PR is intended to fix displaying of 2 plots (images) in the tutorials/images/transfer_learning.
The graphs for the following were not rendered in the **Transfer Learning Using Pretrained ConvNets** tutorial:
- Validation, Test Accuracies
- Effect of Fine Tuning
The same tutorial is unavailable on the tensorflow.org website. Feature Extraction from Pretrained networks and Fine Tuning have been explained very well in this tutorial so it should be added to the links in the official website tutorials.

Fixes display issues in tutorials/images/transfer_learning.ipynb

---

site/en/guide/performance/datasets.md

This updates function references to use the non-deprecated `tf.data.experimental` versions

Update tf.contrib references

---

site/ja/install/gpu.md

This PR is just a split small version of this #442 for reviewers to check the content of PR easily.
@sfujiwara You might have already reviewed site/ja/install/gpu.md. I've made some changes on the gpu.md file to follow up the latest master branch. You can check the below diff:
```
$ git diff 8cdbb909:site/en/install/gpu.md 7022de7:site/en/install/gpu.md
diff --git a/site/en/install/gpu.md b/site/en/install/gpu.md
index 1c10acb3c..1633d5034 100644
--- a/site/en/install/gpu.md
+++ b/site/en/install/gpu.md
@@ -21,13 +21,13 @@ GPU support, choose a stable or development package:
<code class="devsite-terminal">pip install tf-nightly-gpu  # preview</code>
</pre>
-### TensorFlow 2.0 Alpha
+### TensorFlow 2.0 Beta
-[TensorFlow 2.0 Alpha](../alpha) is available for testing with GPU support. To …
```

JA: translation /ja/install/gpu.md

---

site/ja/probability/overview.md

I've translated https://github.com/tensorflow/probability/blob/master/tensorflow_probability/g3doc/overview.md in Japanese.

JA: translation site/ja/probability/overview.md

---

site/en/r2/guide/data.md

Otherwise you will get this error when running the examples:
> module 'tensorflow' has no attribute 'read_file'

Correct tf.read_file() to tf.io.read_file()

---

site/en/tutorials/sequences/recurrent_quickdraw.md

Already working on https://www.tensorflow.org/tutorials/sequences/recurrent_quickdraw
but this fixes the Markdown preview in GitHub.
Fixes https://github.com/tensorflow/tensorflow/issues/30127

Point recurrent_quickdraw images to webserver

---

site/en/r2/guide/data.md

In Tensorflow 2.0 [tf.image.resize_images](https://www.tensorflow.org/api_docs/python/tf/image/resize_images) has been replaced with [tf.image.resize](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/image/resize).

Correct `tf.image.resize_images` to `tf.image.resize`

---

site/en/r2/guide/using_gpu.ipynb

I noticed the hyperlink was throwing a 404 on the website. This should work.

fix wrong hyperlink to distribute_strategy.ipynb

---

site/en/install/pip.html

Commit [7256a3](https://github.com/tensorflow/docs/commit/db026698ed79472677a7b084dba111d3a27256a3) updated the Available packages section to indicate `tensorflow—Latest stable release for CPU-only` is only available for Ubuntu and Windows. This may have been true in March (I am new) but it is not the case today.

Remove OS for tensorflow package

---

site/en/guide/keras.ipynb

When starting the test after the installation of kera, this error show up: change of the deprecated syntax 'tf.VERSION' for 'tf.version.VERSION'

Change of the deprecated syntax 'tf.VERSION' for 'tf.version.VERSION'

---

site/en/r2/tutorials/load_data/tf_records.ipynb

While studying how TensorFlow Datasets work and the TFRecord file format, I went through the [_Using TFRecords and tf.Example tutorial_](https://www.tensorflow.org/beta/tutorials/load_data/tf_records) (r2, TF2 Beta1) and made a few changes in line with the Google Docs guide.
Suggestions include: fix minor typos in a file name (`test.tfrecord` without an "s" versus `images.tfrecords` with an "s" in the end), fix bullet point representation in markdown (replace "-" with "*"), fix the tense of a few verbs to be in a passive voice ("..es" -> "..ed"), capitalize a few letters (e.g. "TensorFlow"), use second person (change from "we" and "our" to "you" and "your"), add backticks/colons/commas where needed, change the copyright year to 2019, fix the "tensors" spelling, change a few paragraph …

Update tf_records.pynb tutorial

---

site/en/r2/tutorials/text/text_generation.ipynb

On line 619, likelihood is spelt liklihood. This issue is not present in the tensorflow 1 equivalent of this tutorial.

Fix Typo: likelihood spelt liklihood

---

site/en/r2/guide/keras/rnn.ipynb

This change rectifies the spelling error where internal is spelled intenral.

typo: change spelling of intenral to internal

---

site/en/r2/guide/data.md

tf.random_uniform(...) doesn't exist in 2.0 where it does in 1.x
https://www.tensorflow.org/api_docs/python/tf/random/uniform
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/random/uniform

tf.random_uniform -> tf.random.uniform

---

site/en/tutorials/load_data/images.ipynb

It is necessary to use softmax as activation to convert raw prediction values to probability distribution.

Use softmax as activation for the dense layer

---

site/en/tutorials/estimators/linear.ipynb

In the "Overview" section, "about" was missing in describing the data content.
In the "Converting Data into Tensors", object was wrongly spelt

Corrected typo and ommission

---

site/en/r2/tutorials/text/nmt_with_attention.ipynb

Current links redirect to https://www.tensorflow.org/tutorials so replace them with the correct links to GitHub.

Replace the links to seq2seq tutorial

---

site/ko/README.md

Summary : removed not-to-translate term "import"(가져오기)
in #808, 'import' is able to translate '가져오기', but he is hesitating to change the word.
From this PR, I suggest to remove 'import'.
Thanks. 👍

KO: ko/README.md not-to-translate term fix

---

site/zh-cn/lite/model/smart_reply/overview.md
site/zh-cn/lite/models/smart_reply/overview.md

lite/models/smart_reply was translated into Chinese.
origin file:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models/smart_reply/overview.md
translated file:
https://github.com/flyyuan/docs/blob/smart_reply_overview/site/zh-cn/lite/models/smart_reply/overview.md

Smart reply overview was translated into Chinese

---

site/zh-cn/lite/guide/build_ios.md

Translated build_ios.md doc for TensorFlow lite guide.
Already signed individual CLA.

zh-CN: build_ios.md for TensorFlow lite guide

---

site/en/r2/guide/estimators/_index.ipynb

Initial port of the [Intro to Estimators](https://www.tensorflow.org/guide/estimators) guide to a TF2 notebook.
Does not run completely since `train_data` needs to be mocked or use a more interesting dataset.

Initial porting of Intro to Estimators to TF2 notebook

---

site/en/r2/tutorials/generative/cyclegan.ipynb

- Separating the cycle loss for F(G(x)) and G(F(y)) results in the
gradient not calculated on the loss of G(F(y)) with respect to G, and
loss of F(G(x)) with respect to F. Therefore they are now combined.
- Redundant gradient tape is removed since persistent is already set to
true.

[CycleGAN Tutorial] Refine the cycle loss function, and remove redundant gradient tape

---

site/en/guide/extend/op.md

I'm not sure if this is a mistake or not but on line 191 there is a comment that says the header file is "kernel_example.h" but on line 213 the include statement refers to it as "example.h" - I assume this was meant to refer to "kernel_example.h".

changed include from "example.h" to "kernel_example.h"

---

site/en/guide/tensors.md

The ordering of the spatial dimensions is mismatching in the running text and the inline python comment. Which one is correct? I think the most common convention is `batch_size x height x width x channels` if `channels_first=False`. See the [TensorFlow Hub documentation](https://www.tensorflow.org/hub/common_signatures/images).

make inline comment match running text

---

site/en/r2/tutorials/eager/custom_training.ipynb

Some suggested (UX) improvements to the _'Custom training: basics'_ r2 (TensorFlow 2 Beta1) tutorial:
- Update and expand `tf.keras` paragraphs with a link to the Keras guide
- Expand the L2 loss section
- Expand the training data synthesis with Gaussian noise section
- Update the training model section
- Add a small explanation of `tf.GradientTape` and `tf.assign_sub`
- Add backticks (`tf.Variable`)
- Change Copyright to `2019`
- Use second person where applicable
- Add/replace commas/colons
- Use em dash (`—`)/replace en dash(`-`)
- Add a `tf.random.normal` reference
- Use % modulo op to print the 'Current loss' in line with the rest of the notebook's style
- Fix labels in a plot (`True W`, `True b`)
- Change "desired" to "target" (commonly used word for `y`)
As before, if you find any …

Update custom_training.ipynb custom training basics tutorial

---

site/en/r2/tutorials/keras/save_and_restore_models.ipynb

Suggestions for the Keras Save and Restore Models tutorial (TensorFlow 2.0 Beta1):
- Add a `save_weights` **in HDF5** section: the TensorFlow default `.ckpt` vs Keras `.h5` weights files were discussed during one of the TF2 community testing calls, sometimes it may create confusion, so maybe we should emphasize how to switch between the two more often in various tutorials, just in case
- Add other minor fixes, suggestions, UX improvements in line with the Google Docs style guide
@lamberta @MarkDaoust @yashk2810 this is the first time I used Colab to make changes, hopefully it didn't break anything important, as Jsons are very delicate

Add `save_weights` in HDF5 to save_and_restore_models.ipynb and other

---

site/en/r2/guide/data_performance.md

Great guide! To enhance UX, maybe we can have Python identifiers in markdown for syntax highlighting in code blocks. Cheers

Add Python to markdown

---

site/ja/guide/keras.ipynb

use tf.version.VERSION because tf.VERSION is deprecated in keras getting started.
> W0731 15:35:56.917445 4494173632 deprecation_wrapper.py:119] From check_import.py:5: The name tf.VERSION is deprecated. Please use tf.version.VERSION instead.

 use tf.version.VERSION because tf.VERSION is deprecated

---

site/en/r2/tutorials/text/transformer.ipynb

I think the positional encoding concatenation part is wrong, because it makes the positional encoding vector as like this, 
PE_pos = [ sin(*) ,...,sin(*),cos(*),...cos(*)] 
But It should be looks like this.
Thus, I changed the code. 
Please take care :)

Revise wrong concatenation at the positional encoding

---

site/en/r2/tutorials/keras/basic_classification.ipynb
site/en/tutorials/keras/basic_classification.ipynb

The current implementation of methods `plot_image` and `plot_value_array` works well when the size of  `predictions_array` is greater than `1`. But this implementation gives error while performing prediction on a single image which is not at `0`<sup>th</sup> position in `test_images`.
---
For example, the current implementation of single image prediction uses the first image from the `test_images`,
```python
img = test_images[0]
print(img.shape)
```
which works well while plotting the value array graph (_the first argument of the `plot_value_array` method is the index of the image being used for the test purpose, which in this case is `0`_),
```python
plot_value_array(0, predictions_single, test_labels)
plt.xticks(range(10), class_names, rotation=45)
plt.show()
```
But, if we use an image …

update plot methods in Make predictions section

---

site/en/r2/guide/autograph.ipynb

The link for AutoGraph Capabilities and Limitations is broken. This PR fixes it. Thanks!

update autograph.ipynb with correct link

---

site/zh-cn/beta/tutorials/keras/save_and_restore_models.ipynb

translate blob/master/site/en/r2/tutorials/keras/save_and_restore_models.ipynb

zh-CN:translate save_and_restore_models.ipynb

---

site/en/guide/autograph.ipynb

minor typos are corrected
benfits -> benefits
autmoatic -> automatic

Fixed minor typo in site/en/guide/autograph.ipynb

---

site/en/r2/guide/keras/rnn.ipynb

"The returned states can be used resume the RNN execution" -> "The returned states can be used **to** resume the RNN execution"

Fix typo in site/en/r2/guide/keras/rnn.ipynb 

---

site/en/install/source.md

Some struggle with choosing the correct version of Bazel for building TF from scratch (see, e.g., https://github.com/tensorflow/tensorflow/issues/24101 ). This patch mentions such a dependency explicitly.

Mention Bazel version dependency

---

site/en/tutorials/keras/classification.ipynb

When we change input test_images from the currently selected image to other in the tutorial, then the prediction will change and reports correctly. But, the static text at the end of the tutorial And the model predicts a label of 2. will not change.
So I changed the static text from And the model predicts a label of 2. to And the model predicts a label as expected.
Thanks

Updated typo

---

site/en/tutorials/load_data/csv.ipynb

fix typo. batch size is 5 rather than 12 in this example.

fix typo of batch size csv.ipynb

---

site/en/tutorials/load_data/images.ipynb

The user did not create this archive. Therefore, saying "You have already created" is incorrect.

Fix wording in Load images tutorial

---

site/en/tutorials/images/cnn.ipynb

Here's the page in question: https://www.tensorflow.org/beta/tutorials/images/intro_to_cnns
It's a fantastically written article, but I found a small typo under the "Create a convolutional base" heading. Additionally, I removed "As you can see" from the final paragraph, given that the same phrase was used at the start of the previous paragraph. As you're reading through the page it can seem a bit clumsy.

Small typo fixes for into_to_cnns.ipynb

---

site/ko/README.md

change directory path 
- TF 2.0(beta): `site/ko/r2` -> `site/ko`
- TF 1.X : `site/ko` -> `site/ko/r1`

KO: fix broken directory path of TF 2.0 and TF 1.X docs

---

site/en/install/source.md

`nightly-devel` is just `devel` now (this has been the case for a while, but I think this page never got updated). I think this is the only fix we need.
Resolves https://github.com/tensorflow/tensorflow/issues/26333.

Update Docker image references

---

site/en/guide/migrate.ipynb

I think the intention here is to only call .take() once after .batch()

take(5) should be called only once

---

site/en/tutorials/images/segmentation.ipynb

Text says "image is normalized to [0, 1]", but it is
normalized to have the range [-1, 1].
Divide images by 255.0 like other tutorials.

Fix normalize in segmentation.ipynb

---

site/en/guide/eager.ipynb

This pull request revives "Summaries and TensorBoard" section to https://www.tensorflow.org/guide/eager with `tf.compat.v2.summary`.
See https://github.com/tensorflow/tensorflow/issues/32588 for the background.

Revise tf.summary section to eager.ipynb with tf.compat.v2.summary

---

site/en/tutorials/distribute/multi_worker_with_estimator.ipynb

The rest of the `model_fn` assumes that the output from the model is logits,
so remove the softmax activation function from the last layer. Training did
not converge in my testing because the loss calculation assumed the inputs
were logits (`from_logits=True`) when they in fact were the output of a softmax.

multi_worker_with_estimator.ipynb: Remove softmax to get logits

---

site/en/guide/distributed_training.ipynb

Fixed broken link at this page:
https://www.tensorflow.org/guide/distributed_training

Fix broken ResNet link in distributed training

---

site/en/guide/keras/overview.ipynb

Fix broken estimators link at this page: [https://www.tensorflow.org/guide/keras/overview](https://www.tensorflow.org/guide/keras/overview)

Fix broken estimators link in Keras overview

---

CONTRIBUTING.md

The word "guide" was duplicated.

Correct a typo in CONTRIBUTING.md

---

site/en/tutorials/images/cnn.ipynb

I noticed that the merged commit #1054 passed only 2 out of 3 checks.
Check failed: `Ubuntu Sanity Check Internal CI build failed`
[Build Status Details](https://source.cloud.google.com/results/invocations/a8758598-e7bc-464a-830a-18dd0d00d80d/targets/tensorflow_docs%2Fubuntu%2Fpresubmit/log) reveal the warning message is:
```
WARNING: Please use 'you' instead of 'we'. See the documentation style (https://www.tensorflow.org/community/contribute/docs_style)
```
I've changed the "we" words to "you" in the file to adhere to the [TensorFlow documentation style guide](https://www.tensorflow.org/community/contribute/docs_style). Hopefully, this should fix the failing check.

Fix: Ubuntu Sanity Check: Internal CI build failed

---

site/en/tutorials/text/word_embeddings.ipynb

When running this notebook from colab Loading text tutorial link is broken and needs file extension to open text.ipynb

Fixed link for Loading text tutorial

---

site/en/guide/keras/overview.ipynb

On [https://www.tensorflow.org/guide/keras/overview](https://www.tensorflow.org/guide/keras/overview):
* fix link paths
* convert links to reference ipynb instead of md

Fix links in keras/overview

---

site/en/tutorials/_index.yaml

Fixed typo in tutorials/_index.yaml

---

site/en/guide/eager.ipynb

Fixes a typo in the Dynamic models example of eager execution.

Fix typo in eager.ipynb

---

site/en/guide/keras/masking_and_padding.ipynb

Added a newline before list so docs show up properly on 
https://www.tensorflow.org/guide/keras/masking_and_padding

Markdown list is not properly displayed

---

site/en/guide/create_op.md

fix typo in 'guide/create_op.md', "input" -> "output"

Fix typo in 'guide/create_op.md'

---

site/en/install/source.md
site/en/install/source_rpi.md
site/en/install/source_windows.md

Fixed typos and updated instructions in source, source_windows source_rpi. 
Fixed typo: Raspian -> Raspbian (source_rpi)
Fixed conflicting instruction in source_windows regarding bazel installation version, (link provided was 0.24.1 while the instructions said the build version should be 0.23.0 or lower) 
Added links to the tested configurations to see compatible bazel versions in source_windows.md and source.md .

Fixed typos. Fixed and enhanced conflicting instructions.

---

tools/tensorflow_docs/vis/__init__.py
tools/tensorflow_docs/vis/webp_animation.py

Here, 
`datya` has been corrected to `data` and  `viaualization` has been corrected to `visualization`

Fixed some spelling errors

---

site/en/install/gpu.md

On ubuntu 18, it's "nvidia-driver-418". However, on ubuntu 16 it's for whatever reason named "nvidia-418", i.e. without the "-driver" part.

Fix Ubuntu 16.04 nvidia driver package name

---

site/zh-cn/tutorials/distribute/multi_worker_with_estimator.ipynb

zh-CN: tutorials/distribute/multi_worker_with_estimator.ipynb

zh-CN: tutorials/distribute/multi_worker_with_estimator.ipynb

---

site/en/tutorials/generative/adversarial_fgsm.ipynb

This PR will fix https://github.com/tensorflow/tensorflow/issues/32715.
https://www.tensorflow.org/beta/tutorials/generative/adversarial_fgsm
The implementaion of FGSM in the doc is incorrect, because the `create_adversarial_pattern` function, which must take the image and the label of the image, takes the image and the predicted probability of the image.
Thus, by this PR, the `create_adversarial_pattern` function is going to take `label` instead of `image_probs` (`== model.predict(image)`), where the `label` is the one-hot vector of the label of the image.

Fix FGSM tutorial

---

site/en/tutorials/text/word_embeddings.ipynb

Removed the code cell that only declare encoder variable.
It is duplicated in the code cell below.

Remove redundant code cell that only declare encoder variable

---

site/en/tutorials/text/word_embeddings.ipynb

There should be a Dense layer with 16 units in the model, according to the description of layers.

Added a missing Dense layer in the model.

---

site/en/api_docs/index.md

Few links were outdated (supported r1 documentation only). Updated according to https://www.tensorflow.org/api_docs

Updated links

---

site/en/tutorials/keras/regression.ipynb

Only fix the URL of [tf.keras.callbacks.EarlyStopping](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/EarlyStopping)

fix broken link to tf.keras.callbacks.EarlySopping

---

site/en/guide/tensor.md

tf.Print() is deprecated since TF 1.13 and not included in TF 2.0, so just remove tf.Print() section.
Thanks.

remove tf.Print() section in tensor.md

---

site/en/guide/saved_model.ipynb

Fixed typos and removed empty `print()` call

Fixed typos and removed empty print() call

---

site/en/guide/data_performance.md

Following changes will apply as per tf 2.0:
+  ```tf.FixedLengthFeature((), tf.string, "")``` to ```tf.io.FixedLenFeature([], tf.string, "")```
+  ```tf.parse_single_example(example, example_fmt)``` to ```tf.io.parse_single_example(example, example_fmt)```
+  ```tf.io.image.decode_image(parsed["image"])``` to ```tf.io.decode_image(parsed["image"])```
For reference, see here: 
+  https://www.tensorflow.org/api_docs/python/tf/io/parse_single_example
+  https://www.tensorflow.org/api_docs/python/tf/io/FixedLenFeature
+  https://www.tensorflow.org/api_docs/python/tf/io/decode_image

Update parse_fn as per tf 2.0 apis

---

site/en/guide/keras/train_and_evaluate.ipynb

I've spotted this (probably unintended) typo on https://www.tensorflow.org/guide/keras/train_and_evaluate

Fix typo in custom metric name

---

site/en/install/lang_c.md

The C Installation page still has the outdated 1.14.0 libraries, although the 1.15.0 ones appear to exist. Therefore, I changed them to the 1.15.0 ones.

Changed C Installation To 1.15.0

---

site/en/api_docs/index.md

Add reference to API docs index page: tensorflow.m (MATLAB bindings for TensorFlow Core, https://github.com/asteinh/tensorflow.m); obeying alphabetical order

Add reference to MATLAB bindings in API docs

---

site/en/tutorials/structured_data/time_series.ipynb

**Note : This is a reapplying of my Pull Request as asked by @MarkDaoust in Pull Request #946** 
**Page concerned :** [Time series forecasting guide](https://www.tensorflow.org/beta/tutorials/text/time_series)
I noticed that the name of the method used for scaling data did not match its description.
- **Normalization** typically means rescales the values into a range of [0,1]. 
- **Standardization** typically means rescales data to have a mean of 0 and a standard deviation of 1 (unit variance).
This can be confusing when you observe data and notice that the values are not between [0,1]. 
[Source](https://towardsdatascience.com/normalization-vs-standardization-quantitative-analysis-a91e8a79cebf)

Update time_series.ipynb - scaling methods 

---

site/en/tutorials/keras/overfit_and_underfit.ipynb

Fixed several spelling and grammatical errors in the tutorial.

Fix typos in overfit_and_underfit.ipynb tutorial

---

site/en/guide/data.ipynb

In the "preprocessing data" section, the "parse_image" method incorrectly reads from a variable called "file_path" instead of from the method parameter "filename".
This doesn't break anything too visibly, but it causes the "Map it over the dataset" example code two cells later to show incorrect labels for the examples it displays.

guide/data.ipynb: Fix bug in parse_image example code.

---

site/en/tutorials/text/image_captioning.ipynb

```len(tokenizer.word_index)``` return all unfiltered vocab size. You filtered this vocabulary while building **_Tokenizer_**.
For example:
```
import tensorflow as tf
tk = tf.keras.preprocessing.text.Tokenizer(num_words=2)
texts = ["AAA BBB", "CCC DDD", "AAA DDD"]
tk.fit_on_texts(texts)
print(tk.word_index)  
print(len(tk.word_index))
```

fix vocabulary size based on all unique word count

---

site/en/tutorials/structured_data/time_series.ipynb

This change is compatible Python 2/3.
Tested with length < 0, == 0 and > 0.

time_series.ipynb: simplify create_time_steps

---

tools/spelltest/spelltest.sh

Check nbconvert ran as it's supposed to.
Virtualenvs can get hosed when upgrading Python.

Err check for spelltest

---

site/en/tutorials/generative/dcgan.ipynb
site/ko/tutorials/generative/dcgan.ipynb
site/zh-cn/tutorials/generative/dcgan.ipynb

Changed the link from https://www.kaggle.com/jessicali9530/celeba-dataset/home to https://www.kaggle.com/jessicali9530/celeba-dataset . I The original link returns page not found.

Fix CelebA dataset link in DCGAN tutorial.

---

site/en/install/_index.yaml

When you arrive to https://www.tensorflow.org/install.
The command said you would run a Jupyter notebook on the container start, but you need to have the `-jupyter`image tag to do it. I was confused when I wanted to follow the instructions.

Fix installation docker command error

---

site/en/r1/guide/extend/architecture.md

Replace inline image syntax with img tag to specify image size on GitHub.

Replace inline image syntax with img tag to specify image size

---

site/en/install/gpu.md

tensorrt version 6.0.1 is needed for v2.1 of tf as per error messages. modifying the command to reflect tensorrt 6.0.1

updated to reflect tensorrt  change for v2.1

---

site/en/install/gpu.md

Without the `libnvinfer-plugin6` package, Tensorflow apparently fails to load TensorRT with the following error:
W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Adding the package solves the issue

Fix install instructions for TensorRT

---

site/en/tutorials/estimator/linear.ipynb

This tiny change fixes a comment I noticed while reading docs.

estimator/linear.pynb: Fix typo with duplicate 'take'

---

site/en/install/pip.html

TensorFlow 2.1.0 was built with Visual Studio 2019, which requires an additional DLL from Visual Studio 2019, `msvcp140_1.dll`. I updated the internal checker for this, but being unfamiliar with the installation instructions, I didn't update this page when the change occurred.
See also: tensorflow/tensorflow/commit/78ddcded185e60f83743faa194178a8e5979757b, https://github.com/tensorflow/tensorflow/issues/35036

Update installation instructions for VS 2019 (post-2.1.0) packages

---

site/en/install/gpu.md

Clarify that CUDA Ubuntu 16.04 Install is for version 10.1
Add `libnvinfer-plugin6=6.0.1-1+cuda10.1` for TensorRT
This PR supersedes  https://github.com/tensorflow/docs/pull/1403 since I can't seem to add commits there.

Update GPU install Ubuntu 16.04

---

site/en/install/_index.yaml
site/en/install/pip.html

There are issues like [#33374](https://github.com/tensorflow/tensorflow/issues/33374) which asks for installing tf in python 3.8 but as of now, it is not supporting. Also, there are many issues being made everyday about the same problem. So, this is the correction in the doc to illustrate that tf supports python version 3.4 to 3.7.

Python version corrected in doc

---

site/en/install/gpu.md

The issue seems to appear while running line 102 of this doc to install CUDA on Ubuntu 18.04. When I run the following script as it's written in the documentation, I ran to an error.
<code class="devsite-terminal">sudo apt-get install --no-install-recommends \
cuda-10-1 \
libcudnn7=7.6.4.38-1+cuda10.1  \
libcudnn7-dev=7.6.4.38-1+cuda10.1
</code>
The error is as follows: 
```
cuda-10-1 : Depends: cuda-runtime-10-1 (>= 10.1.243) but it is not going to be installed
Depends: cuda-demo-suite-10-1 (>= 10.1.243) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
After trying different ways to overcome this issue, it seems like it can be solved by explicitly determining the driver version as version 430. I cleaned the whole previously installed …

Fix driver version to install CUDA on ubuntu 18.04

---

site/en/guide/gpu.ipynb
site/en/tutorials/estimator/boosted_trees.ipynb
site/en/tutorials/estimator/boosted_trees_model_understanding.ipynb

```
./tools/nbfmt.py --ignore_warn --preserve_outputs \
site/en/guide/gpu.ipynb   site/en/tutorials/estimator/boosted_trees.ipynb \
site/en/tutorials/estimator/boosted_trees_model_understanding.ipynb
```

Fix private outputs on notebooks with saved outputs

---

site/en/api_docs/_book.yaml
site/en/api_docs/index.md
site/en/install/lang_go.md
site/en/r1/guide/version_compat.md

Since [Pkg.go.dev](https://pkg.go.dev) is now the officially suggested documentation and discovery resource for open-source projects, the TensorFlow docs should automatically point there instead of [GoDoc.org](https://godoc.org/).
This PR updates all relevant links.

Update Go documentation links to pkg.go.dev

---

site/en/tutorials/keras/text_classification.ipynb

1) Updated the notes on Dense layer using `sigmoid` activation, when it is actually using `linear` + `BinaryCrossentropy`'s  "from_logits" option.
2) The notebook installs TF 2.2.0 dev. However, for TF 2.1.0, "padded_shapes" is a mandatory agurment for the `padded_batch()` function. Of course, this change is subjective as it may affect readability of the tutorial.

Updated notes on Dense layer using `linear` instead `sigmoid` and tf 2.1.0 compatible args

---

site/en/tutorials/images/transfer_learning.ipynb

To avoid confusion, add tf. that are not written in code.
And as mentioned in [#1447 ](https://github.com/tensorflow/docs/pull/1447#issuecomment-583231323) I checked all files and edit which contains `kreas = tf.keras` on top.

add `tf.` for prediction_layer in `/tutorials/images/transfer_learning`

---

site/en/tutorials/generative/adversarial_fgsm.ipynb

Minor edits to fix typo, punctuation, and ambiguous expression (changed "gradients are used with respect to..." to "gradients are taken with respect to...") to improve readability

Minor typo and punctuation fix

---

site/en/install/source.md

Changed command-line option to "--gpus all" as "--runtime=nvidia" kept returning an error.
Added note to do a: git pull as well much like the CPU instructions to make this clear.

Correct Docker Build with GPU

---

site/en/tutorials/load_data/tfrecord.ipynb

The phrase was:
`Applies to a tuple of arrays, it returns a dataset of tuples`
, where it should be Applied, which is more correct and matches the phrase above (line 533)
Yes, I've signed the CLA

Changed tense which confused me

---

site/en/guide/keras/train_and_evaluate.ipynb

The document states that string identifiers can be used as shortcut, yet the example given is no different from the compilation method shown in the code block above (presumably without strings identifiers, which is also confusing given that the metric was defined with a string identifier). The edit adds clarity by demonstrating how models can be compiled with and without string identifiers.

Edit string shortcut for model compilation

---

site/en/r1/tutorials/sequences/audio_recognition.md

closes https://github.com/tensorflow/tensorflow/issues/34460
Changed the url according to the script `tensorflow/examples/speech_commands/train.py` .
Also, the previous url has some certification error

change download url for dataset

---

site/en/tutorials/keras/classification.ipynb

The last dense layer is a logits layer, instead of a softmax layer.

Fix description error in classification tutorial

---

site/en/install/gpu.md

The guide on CUDA installation has a small bug. The apt-key needs to be installed before the package can be installed.
``` bash
sudo dpkg -i cuda-repo-ubuntu1804_10.1.243-1_amd64.deb
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
```
``` bash
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
sudo dpkg -i cuda-repo-ubuntu1804_10.1.243-1_amd64.deb
```

apt-key needs to be installed before package installation: guide on CUDA installation 

---

site/en/guide/keras/functional.ipynb

There is a minor formatting error where `Sequential` is formatted as S`equential`

Fix minor typo

---

site/en/tutorials/load_data/images.ipynb

The current [images tutorial](https://www.tensorflow.org/tutorials/load_data/images) displays the following error: `ERROR: tensorflow 2.1.0 has requirement gast==0.2.2, but you'll have gast 0.3.3 which is incompatible.`. This is presumably caused by the use of TF nightly, and can easily be resolved by using TF 2.X (2.1) instead. I have verified that the notebook runs fine with this setting on Colab. Thanks for reviewing!

Replace nightly with TF 2.x

---

site/en/tutorials/customization/custom_layers.ipynb

This tutorial uses `add_variable`, which is a deprecated function for newer versions of TensorFlow. Replaced this function with `add_weights` to keep the tutorial up-to-date with TF API.

Replaced deprecated function

---

site/en/tutorials/text/nmt_with_attention.ipynb

```python
w = w.rstrip().strip()
```
is equivalent to 
```python
w = w.strip()
```
It's better to use the simpler version.

[MRG]Remove unnecessary rstrip

---

site/en/tutorials/images/data_augmentation.ipynb

There is a redundancy is the use of "available" in the following sentence: 
```
"See the `tf.image` reference for available augmentation options available."
```
This PR proposes a correction.

[MRG] Rephrase to remove redundant word "available"

---

site/en/r1/guide/extend/architecture.md

Hi, there is a broken link for the distributed Tensorflow. And the distributed_strategy seems to be the closest link, so I changed the link path to ../distribute_strategy.ipynb

Fixed broken link of the distributed Tensorflow

---

site/en/tutorials/keras/overfit_and_underfit.ipynb

The old linked websites certificate is out of date.

Changed dataset link to make it work again.

---

site/en/tutorials/load_data/csv.ipynb

In this load_data/csv tutorial (https://www.tensorflow.org/tutorials/load_data/csv), the final prediction values are weird. For instance:
```
Predicted survival: -236.86% | Actual outcome: SURVIVED
Predicted survival: -100.17% | Actual outcome: DIED
Predicted survival: -238.74% | Actual outcome: DIED
Predicted survival: 147.69% | Actual outcome: DIED
Predicted survival: 12.94% | Actual outcome: SURVIVED
```
This PR adds the `sigmoid` activation function to the last `Dense` layer, keeping the result between 0 and 1:
```
Predicted survival: 0.01%  | Actual outcome:  SURVIVED
Predicted survival: 100.00%  | Actual outcome:  DIED
Predicted survival: 0.02%  | Actual outcome:  SURVIVED
Predicted survival: 99.86%  | Actual outcome:  DIED
Predicted survival: 2.43%  | Actual outcome:  SURVIVED
```

Add proper activation function

---

site/en/tutorials/customization/custom_training.ipynb

Fixes [#38067](https://github.com/tensorflow/tensorflow/issues/38067).  
I agree with @Arktius that even if the loss here given is MSE and it is not affected by order of params, it is good to follow the convention of every loss function that `y_true` should be first and then `y_pred`.  
@MarkDaoust and @mihaimaruseac , Please review.

Corrected order of params of loss fn in custom_training.ipynb

---

site/en/guide/data.ipynb

I'm not sure whether it's intended for the documentation to run on every platform. I think this change slightly decreases the readability.
Note that `pathlib` does not explicitly provide the `pathlib.os` variable, it's simply available because it imports `os` internally. It could be cleaner to explicitly `import os` and change this to `os.sep` instead of `pathlib.os.sep`.
p.s: made a new PR because the email in the commits was `noreply@user.github.com`

fix separator usage to work on windows

---

site/en/tutorials/quickstart/advanced.ipynb

Surround binary operators with a single space on either side in the format string method of the [Quickstart for experts](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/advanced.ipynb) notebook.
Thanks !

PEP 8 fix in Quickstart for experts.

---

site/en/tutorials/text/nmt_with_attention.ipynb

As pointed out in tensorflow/tensorflow#28371, the `max_length` function is unnecessary since `tf.keras.preprocessing.sequence.pad_sequences` called within `tokenize` already pads sequences by `maxlen`, which defaults to the length of the longest sequence. Therefore, the maximum length can simply be obtained by examining its shape.

Delete unnecessary max_length function

---

site/en/tutorials/generative/style_transfer.ipynb

This PR resolves a very minor typo/punctuation error found in the `style_transfer.ipynb` tutorial.

Resolve minor typo and punctuation issue

---

site/en/tutorials/keras/overfit_and_underfit.ipynb

The original sentence seemed ambiguous, with missing words potentially. Here's a suggestion to make it easier to understand.

Typo in site/en/tutorials/keras/overfit_and_underfit.ipynb 

---

site/en/tutorials/generative/adversarial_fgsm.ipynb

Previously it was [0,1] but the input mobilenetV2 needs it in the form of [-1,1]. So made changes in the notebook to accommodate the change.

Changed the input range for mobilenetV2

---

site/en/tutorials/text/transformer.ipynb

Small typo fix in narrative documentation / tutorial.

Fix typo 'peaking' -> 'peeking'.

---

site/en/community/contribute/docs.md

3 whitespaces were added after https:// in this commit https://github.com/tensorflow/docs/commit/d18c8352fd3fa57fbabdb239984e59c684a9fb52#diff-89f8d80a3fb313d1d00abbc99eb5c180
also extra typo at the bottom

fix link on contribute/docs page

---

site/en/guide/autodiff.ipynb

In the comment it said 'dz_dx', however 'dz_dy' is meant

Fix comment in autodiff.ipynb

---

site/en/install/source.md

Fix numpy to pre-1.19.0 because of breaking ABI change in numpy 1.19.0 (numpy/numpy#15355). Because of this change, TF source builds break with numpy 1.19.0.
See tensorflow/tensorflow#40688.

Fix numpy version to pre-1.19.0

---

site/en/install/source.md

If the older command was used bash gave the following error:
1.19.0: No such file or directory

enclosed numpy<1.19.0 in ' ' in the dependencies of build from source for Linux page.

---

site/en/guide/migrate.ipynb

>A v1.variable_scope is effectively a layer of its own. So rewrite it as a tf.keras.layers.Layer. See the guide for details.
>
>The general pattern is:
>
>- Collect layer parameters in __init__.
>- Build the variables in build.
>- Execute the calculations in call, and return the result.
>
>The v1.variable_scope is essentially a layer of its own. So rewrite it as a tf.keras.layers.Layer. See the guide for details.
First sentence is almost duplicate with last sentence. I just remove the first sentence.
And fix a typo "how to build a tool fr a similar use-case." --> "how to build a tool **for** a similar use-case."
Thanks. :)

Remove duplicate sentence & fix a typo

---

site/en/tutorials/keras/text_classification.ipynb

In the last section we have:
"This isn't the case for the validation loss and accuracy—they seem to peak after about twenty epochs."

Increase epochs to 30 to match text

---

site/en/tutorials/images/classification.ipynb

The correct size of batch is 128. Replace 32 with 128.

Fix a wrong batch size in tutorial

---

site/en/tutorials/keras/overfit_and_underfit.ipynb

This PR fixes the issue about the failure to open the TensorBoard viewer in the section "View in TensorBoard".
To reproduce this, you may need to "Factory reset runtime".
This is caused by skipping to load the TensorBoard notebook extension. So I add a few lines of comments and codes to load it.

Fix tutorials/keras/overfit and underfit: failed to open TensorBoard

---

site/en/community/contribute/code_style.md

Towards https://github.com/tensorflow/tensorflow/issues/41077. Not sure which flags you invoke `clang-tidy` with though.
`clang-format` is also available since Ubuntu 16.04: https://packages.ubuntu.com/search?keywords=clang-format

Add clang-format install instructions to docs

---

site/en/community/contribute/code_style.md
site/en/guide/create_op.md
site/en/guide/profiler.md
site/en/install/_index.yaml
site/en/install/docker.md
site/en/install/lang_c.md
site/en/install/lang_go.md
site/en/install/lang_java.md
site/en/install/pip.html
site/en/install/source.md
site/en/r1/guide/debugger.md
site/en/r1/guide/extend/op.md
site/en/r1/guide/performance/overview.md

- Removed Python 2 from a bunch of pages where it seemingly was missed during EOL clean up.
- Changed Docker install page as `py3` tag was dropped. Added `custom-op` tag while there.
- [Fixed ](https://github.com/tensorflow/docs/compare/master...Molkree:remove_python_2?expand=1#diff-a2de1331b653964bd3ba0a0031add631L420)`tf.contrib.eager.num_gpus()` in install instructions as it's not available in TF2. Noticed it last year and it's still not fixed D: It even had [issue](https://github.com/tensorflow/tensorflow/issues/33396) created by someone.
- And some extra typo fixes I noticed.

Remove Python 2 mentions

---

site/en/tutorials/load_data/images.ipynb

As [the documentation](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#list_files) states, `list_files()` shuffles filenames by default. So even though `shuffle()` with `reshuffle_each_iteration=False` is used after it, the dataset is still shuffled each iteration because of  `list_files()` default behavior.
This leads to approximately 80% elements of `val_ds` to be from `train_ds` (because `train_ds` indeed contains 80% of all the data). I've used this code to calculate the size of intersection:
```
def get_intersect_len(train, validation):
train_set = set()
for file in train:
train_set.add(file.numpy())
validation_set = set()
for file in validation:
validation_set.add(file.numpy())
return len([path for path in validation_set if path in train_set])
get_intersect_len(train_ds, …
```

Fix intersection of train and validation sets when using tf.data

---

site/en/tutorials/images/transfer_learning.ipynb

This is from [#41413](https://github.com/tensorflow/tensorflow/issues/41413) in *tensorflow/tensorflow* by HaraBeron.
In this tutorial raw prediction values (form_logit=True) are used. So we have negative values and positive values, while
"prediction will be treated as a logit, or a raw prediction value. Positive numbers predict class 1, negative numbers predict class 0."
According to [https://www.tensorflow.org/api_docs/python/tf/keras/metrics/BinaryAccuracy](https://www.tensorflow.org/api_docs/python/tf/keras/metrics/BinaryAccuracy)
As per default, threshold value to classify is 0.5:
>tf.keras.metrics.BinaryAccuracy(
>    name='binary_accuracy', dtype=None, threshold=0.5
>)

Threshold to be set 0 when using binary accuracy with raw prediction values (from_logits=True)

---

.github/workflows/label-lgtm.yaml
.github/workflows/welcome.yaml
tools/tensorflow_docs/tools/README.md

Add GitHub Actions for:
- Add welcome comment with Colab preview links, tensorflow-docs tools, and link to nbreview.com
- Apply community "lgtm" label on any PR approval or comment.
GH Actions tested here: https://github.com/lamberta/tf-docs/pull/3
Can now remove tfdocsbot@ from the tensorflow/docs repo.
Also adds README doc for tensorflow-docs notebook tools.

GitHub actions pr workflows

---

site/en/install/gpu.md

Update GPU docs to document error that users may see when PTX is absent. 
This can happen because TF >= 2.3 has dropped PTX to reduce TF pip package size.
Fixes #41892

Update docs to reflect error when PTX is not present

---

site/en/guide/variable.ipynb

Hey, the very last sentence in the [Variable guide](https://www.tensorflow.org/guide/variable) had a typo in the link text.

[Guides] Fix typo in Variable guide

---

site/en/tutorials/structured_data/time_series.ipynb

changed end of section 2 split: 
from: The code above took a batch of 2, 7-timestep windows, with 19 features 
to: The code above took a batch of 3, 7-timestep windows, with 19 features

documentation typo: batch of 2  should be batch of 3

---

site/en/tutorials/reinforcement_learning/actor_critic.ipynb
site/en/tutorials/structured_data/time_series.ipynb

1. 'widow' --> 'window'
2. 'batch of 2' --> 'batch of 3'
```
example_window = tf.stack([np.array(train_df[:w2.total_window_size]),
np.array(train_df[100:100+w2.total_window_size]),
np.array(train_df[200:200+w2.total_window_size])])
```
The above snippet relating to change 2. shows three slices, implying m = 3,
i.e. 'batch of 3' instead of 2
modified:   site/en/tutorials/structured_data/time_series.ipynb

Fix typo in 'time_series.ipynb' notebook

---

site/en/tutorials/distribute/multi_worker_with_keras.ipynb

This PR updates the **[TensorFlow Multi-worker training with Keras](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras)** notebook by addressing https://github.com/tensorflow/tensorflow/issues/41257 and potentially helping with issues, such as https://github.com/tensorflow/tensorflow/issues/39922:
- Provided a sentence with an example of 2 workers in `TF_CONFIG` (background: to create multiple workers on external IP addresses/ports, you configure `TF_CONFIG` on each worker)
- Made a small change to the section that explains how to turn off automatic manual sharding for training in `tf.data.experimental.DistributeOptions` for clarity
Thank you @guptapriya and @lamberta

Enhance the TensorFlow Multi-worker training with Keras tutorial - provide an example of 2 workers in TF_CONFIG

---

site/en/guide/tf_numpy.ipynb

Hi @yashk2810 @lamberta @guptadhaval18 Thank you for the awesome work on the [TensorFlow NumPy guide](https://www.tensorflow.org/guide/tf_numpy?hl=el).
I've noticed a few typographical errors and created this PR to fix them + add some minor improvements to the guide. (There're a few things I'm not 100% sure about - see below.)
The notebook was originally edited in Google Colab and then run through the `tensorflow_docs.tools.nbfmt` tool.
Here's a summary of the proposed changes:
1. Split a verb (a typo: "checkout" -> "check out") and combine sentences -> _You can do X for reason Y and also do Z_.
```diff
- "Checkout the [NumPy broadcasting guide](https://numpy.org/doc/stable/user/basics.broadcasting.html). Also compare this with [TensorFlow broadcasting …
```

Enhance the TensorFlow NumPy guide, fix typographical errors

---

.github/workflows/bot-nightly.yaml

Adds nightly workflow to generate notebooks and sync the Keras guides from https://github.com/keras-team/keras-io/tree/master/tf
These updates will live on the `snapshot-keras` branch.
Tested in https://github.com/lamberta/tf-docs/runs/1162780925?check_suite_focus=true
Commit: https://github.com/lamberta/tf-docs/commits/snapshot/keras
ref: b/169166095

Add nightly GitHub Actions workflow to sync Keras guides.

---

site/en/tutorials/structured_data/time_series.ipynb

There was some line that doesn't follow the lint style before.
So, the CI pipeline failed if pr changes time-series.ipynb even if such pr follows lint style.
After this pr accepted, some pr should fetch origin and re-test CI pipeline: #1697, #1694, #1688, ...

Fix to follow google style for time-series.ipynb

---

site/en/tutorials/generative/autoencoder.ipynb

encoding_dims variable is not used, so encoded dimensions will not change regardless of how the class is initialized.

fix bug - variable not used as intended

---

site/en/tutorials/generative/deepdream.ipynb

In the DeepDream tutorial, the `tf.roll` op is being used inefficiently by using 2 operations to roll two dimensions one at a time. The `tf.roll` supports the ability to shift multiple dimensions simultaneously so instead of doing:
```python
shift = tf.random.uniform(shape=[2], minval=-maxroll, maxval=maxroll, dtype=tf.int32)
shift_down, shift_right = shift[0],shift[1] 
img_rolled = tf.roll(tf.roll(img, shift_right, axis=1), shift_down, axis=0)
```
Why not do the equivalent in one `tf.roll` operation:
```python
shift = tf.random.uniform(shape=[2], minval=-maxroll, maxval=maxroll, dtype=tf.int32)
img_rolled = tf.roll(img, shift=shift, axis=[0,1])
```
That way we can showcase how to use `tf.roll` in a better way.

DeepDream : use a single `tf.roll` op to shift the two dimensions instead of two ops

---

.github/workflows/ci.yaml

Add notebook outputs check to GitHub Actions CI.
Tested in https://github.com/lamberta/tf-docs/pull/7
This was originally part of the `private_outputs` check but that was removed and hasn't been used in other CI for a while.

CI: Check that output cells are removed from notebooks

---

site/en/install/lang_c.md

Instead of 2.3.0 release, use the last patched version. This way, people will always get the latest C library.

Change download link to the 2.3.1 release

---

site/en/install/lang_java.md

Hi, this PR is to replace the actual install page for Java with instructions for the new [TensorFlow Java](https://github.com/tensorflow/java) maintained by SIG JVM and that has been released last week. Current TF Java from the main TF repository is now officially deprecated.
Note to the approvers: please can you squash all commits into a single one when merging? thank you.
CC\ @MarkDaoust , @martinwicke

Update TensorFlow Java installation instructions

---

site/en/tutorials/audio/simple_audio.ipynb

Hey @lamberta @MarkDaoust and team. Thanks for the new [Simple audio recognition tutorial](https://www.tensorflow.org/tutorials/audio/simple_audio).
I had a quick look and came up with a few alterations and suggestions that you may find useful.
Feel free to ignore any of these or edit the stuff directly.
---
- Change the language in the step where the reader is importing (not installing) TF and several other libraries/APIs, such as Seaborn, matplotlib, IPython, NumPy, and Keras modules:
```diff
- Let's install TensorFlow to get started.
+ Import necessary modules and dependencies.
```
or something like that.
---
- In the beginning of the _Import the…dataset_ section, the description of what the reader will be doing should probably explain what the user - not the script - will be doing by …

Enhance the TensorFlow audio recognition tutorial

---

site/en/tutorials/distribute/multi_worker_with_keras.ipynb

The existing link does not work.

Fix incorrect link to save/restore model in multi-worker training tutorial

---

site/en/guide/migrate.ipynb

Splitting PR https://github.com/tensorflow/docs/pull/1736 into smaller digestible bits.
- Also proposing to use "2.x" instead of "2.0" since we're currently on v2.4.
Cheers @lamberta @MarkDaoust

Lint TensorFlow: Migrate your TensorFlow 1 code to TensorFlow 2

---

site/en/guide/tf_numpy.ipynb

Fix section links (it doesn't work when first letter is in upper case).
Measure vectorized/unvectorized code the same number of times.

Fix some typos in TF NumPy guide

---

site/en/tutorials/text/word_embeddings.ipynb

In the docs present
The tensorboard is not loaded with the `%load_ext tensorboard`. In my opinion tensorboard would run in colab after the tensorboard is externally loaded in the colab notebook first.
I have managed to add the same to first load and then host tensorboard.

Externally loading the tensorboard

---

site/en/guide/distributed_training.ipynb

`tf.config.list_physical_devices('gpu')` does not correctly list the GPUs, changing to `GPU` fixes it. Reference: https://www.tensorflow.org/api_docs/python/tf/config/list_physical_devices

Fix argument for listing GPU

---

site/en/guide/basic_training_loops.ipynb

In the loss visualization step, the parameters for the loss function were in the wrong order (while this doesn't affect the outcome, it may be confusing).

Switched parameters in loss function in file site/en/guide/basic_training_loops.ipynb

---

.github/workflows/bot-pr-new.yaml

set-env is deprecated for GitHub Actions env vars. Update to [new style](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable).
Tested here: https://github.com/lamberta/tf-docs/pull/9

Use updated style for GitHub Action env vars

---

site/en/guide/basic_training_loops.ipynb

There's a broken link on `basic_training_loops.ipynb` to `distributed_training.ipynb`
https://www.tensorflow.org/guide/basic_training_loops#next_steps

Fix link bug from 'basic_training_loops.ipynb' to 'distributed_training.ipynb'

---

site/en/tutorials/images/segmentation.ipynb

Removing this assignment results in an identical model and less confusing code

Remove unused "x = inputs" assignment

---

site/en/install/_index.yaml
site/en/install/pip.html

This was not yet reflected on https://www.tensorflow.org/install and https://www.tensorflow.org/install/pip
This PR removes the mentions of Python 3.5 on these pages.

set minimum Python version to 3.6 (since TF 2.4)

---

site/en/tutorials/images/segmentation.ipynb

I followed this tutorial but my program wasn't working. The cause was that I had created a list of layers, but it was supposed to be a list of layer outputs. These are quite different things.

Rename variable 'layers' - it does not contain layers

---

site/en/tutorials/keras/text_classification.ipynb

Providing filename with extension results in a file on disk called "aclImdb_v1.tar.gz.tar.gz"
`get_file` appears to want a filename without an extension (though the documentation for it is unclear)

Stop doubling up on ".tar.gz" extension

---

site/en/tutorials/generative/pix2pix.ipynb

I was confused by this reference to an as-yet-undefined variable. It's not an error as long as the function is not called, but it's bad style

Define loss_object before usage in generator_loss function

---

site/en/tutorials/keras/save_and_load.ipynb

I was confused about this isolated `batch_size` variable - turns out it's (ab)using the fact that 32 is the current default batch size if unspecified
But if we need to know the batch size, we should specify it

Don't guess at default batch size

---

site/en/guide/data.ipynb

The link to Time series forecasting from the data input pipelines page
was wrong.
Fixes tensorflow/tensorflow#48123

Fix wrong link in data input pipelines page

---

site/en/tutorials/text/solve_glue_tasks_using_bert_on_tpu.ipynb

A few small changes: "recommended", "Colab", "error", "BERT"

Nit: fix small typos in the Solve GLUE tasks using BERT on TPU tutorial

---

site/en/install/lang_java.md

Please merge this changes to reflect the installation guide to the latest release of TensorFlow Java (0.3.1)
Note: I was under the impression that I've already proposed changes in the main `/tensorflow/docs` for the preview 0.3.0 release but cannot find any trace of that. But if there is any, please ignore my previous request and only consider this new one instead.
CC\ @MarkDaoust

Upgrade Java installation guide to 0.3.1

---

site/en/community/contribute/community.md

Fixes https://github.com/tensorflow/community/issues/206
We could reintroduce something if/when we will find an operative plan for https://github.com/tensorflow/community/issues/29

Remove roadmap broken link

---

site/en/community/contribute/code_style.md
site/en/install/source_windows.md

- Simplify the description on how to access the `pylintrc` file -- no need to use `wget`, it is available in the TF checkout.
- I found two more places where Python 3.5 is mentioned. Python 3.5 is not supported any more since TF 2.4.

pylintrc location and Python 3.5

---

tools/tensorflow_docs/tools/.pre-commit-hooks.yaml
tools/tensorflow_docs/tools/README.md

Added a pre-commit hook that automatically calls nbfmt on every commit.
This uses the https://pre-commit.com/ framework.
To use it in another repo, the repo would need a .pre-commit-config.yaml file with the following contents:
```
repos:
- repo: https://github.com/tensorflow/docs
rev: 6dc5e8258b871233e1dd373b49576f9755153bc2
```
Someone who clones that repo for development would then install the hook with:
```
pip3 install pre-commit
pre-commit install
```

Added pre-commit hook for nbfmt

---

site/en/tutorials/load_data/tfrecord.ipynb

Fixed wrong link in ```/site/en/tutorials/load_data/tfrecords.ipynb```
https://www.tensorflow.org/guide/datasets -> https://www.tensorflow.org/guide/data

Fix wrong link

---

site/en/guide/autodiff.ipynb

Comment in intermediate results incorrectly states "dz_dx = 2 * y". It should state "dz_dy = 2*y" and proceeding with the chain rule: "dz_dx = dz_dy * dy_dx where dz_dy = 2 * y and y = x ** 2"

Fixing erroneous comment in Intermediate Results section

---

site/en/guide/checkpoint.ipynb

Correction of a typo; from "vartiable's key" to "variable's key".

Updating checkpoint.ipynb by correcting a typo

---

site/en/tutorials/images/data_augmentation.ipynb

Hi. The data augmentation notebook has an unused import, related to the dataset mnist.
Though it's a minor issue, it nevertheless may confuse people why the mnist is being import if throughout the entire notebook another dataset is being used (flowers).

Remove unused import in data augmentation notebook

---

site/en/tutorials/keras/classification.ipynb

Addresses all improvements listed at [#47552](https://github.com/tensorflow/tensorflow/issues/47552) except point (3).
For point (3), specifying `unit = 128` for a required parameter is unnecessarily verbose in my opinion (https://python-docs.readthedocs.io/en/latest/writing/style.html). Let me know if you feel this needs to be changed.
Fixes: tensorflow/tensorflow#47552

Add more hyperlinks for improved understandability

---

site/en/guide/distributed_training.ipynb

This PR replaces an older PR - the APIs in TensorFlow distribution strategies - `tf.distribute` - have changed and the content has evolved. PTAL @lamberta 👍 
Notable changes for improved UX:
- Add a video description: _"Inside TensorFlow: `tf.distribute.Strategy`"_
```
For a deeper understanding of the concepts, watch the deep-dive presentation—[Inside TensorFlow: `tf.distribute.Strategy`](https://youtu.be/jKV53r9-H14). This is especially recommended if you plan to write your own training loop.
```
- Spell out **NCCL**: _"NVIDIA Collective Communication Library ([NCCL](https://developer.nvidia.com/nccl))"_.
- Add a Wiki link to **Remote Procedure Call (RPC)** (Wiki: _"In distributed computing, a remote procedure call (RPC) is when a computer program causes a procedure (subroutine) to …

Minor revision of the TF Distributed training guide

---

site/en/install/source.md
site/en/install/source_windows.md

PR corrects required Bazel version from 3.1.0 to 3.7.2 for TensorFlow 2.5.0.

update minimum required bazel version for 2.5.0

---

site/en/tutorials/structured_data/imbalanced_data.ipynb

In [tutorials/structured_data/imbalanced_data](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/structured_data/imbalanced_data.ipynb) the section "[Plot the ROC](https://www.tensorflow.org/tutorials/structured_data/imbalanced_data#plot_the_roc)" is repeated, the second one should be "[Plot the AUPRC](https://www.tensorflow.org/tutorials/structured_data/imbalanced_data#plot_the_roc_2)".

Fix repeated title in tutorials/structured_data/imbalanced_data

---

site/en/guide/function.ipynb

Nearly the same as old PR https://github.com/tensorflow/docs/pull/1779 (linting). Fresh fork. PTAL @lamberta 
Notable changes:
- Add a link to the Eager mode notebook:
```
In TensorFlow 2, [eager execution](eager.ipynb) is turned on by default.
```
- Add a short `pdb` description + link to the Python debugger:
```
`pdb` (the [Python debugger](https://docs.python.org/3/library/pdb.html)) can help you understand what's going on during tracing. (Caveat: `pdb` will drop you into AutoGraph-transformed source code.)
```
- "NumPy"

Minor revision of the TF Better performance with `tf.function` guide

---

site/en/tutorials/generative/autoencoder.ipynb

Hi!
`preds` used in `print_stats` refers to a variable defined in next cell so not using it will result in `print_stats` fail.

[tutorials/generative] Use passed argument in `print_stats`

---

site/en/install/gpu.md

Currently the software requirements specified for the TensorFlow 2.5.0 GPU installation list that CUDA 11.2 requires a driver version of `460.x` but actually it only requires a driver version of `450.80.02`. See Table 1 from NVIDIA's CUDA compatibility chart: https://docs.nvidia.com/deploy/cuda-compatibility/index.html

Fix NVIDIA GPU driver requirement for CUDA 11.2

---

site/en/tutorials/structured_data/time_series.ipynb

While the pandas dataframe seems to be in UTC (my inspector shows 'Z'  for zulu timezone, =UTC), Using datetime.datetime.timestamp seems to interpret the time as the local time. This results in different outputs depending on your local timezone (clearly visible in the ' Time of Day signal plot' ).
Using the pandas equivalent function works uniformly independent from local environment.

use Pandas timestamp instead of datetime timestamp

---

site/en/install/_index.yaml

Since Python 3.9 is officially supported, I propose to fix the version to 3.9.
Related Issues: https://github.com/tensorflow/tensorflow/issues/50973

Fixing the Python version 3.8 to 3.9

---

site/en/guide/data.ipynb

Current link https://www.tensorflow.org/tutorials/load_data/pandas returns 404:
New link: https://www.tensorflow.org/tutorials/load_data/pandas_dataframe

Fixed link to the pandas dataframe tutorial

---

site/en/guide/intro_to_graphs.ipynb

In the given examples, the unused function is tf.gather instead of tf.math.bincount.
Also, in the webpage, the output of the first example (unused_return_eager) is also wrong. It should report an error instead of a tf.Tensor as displayed in the current webpage.

typos in the subsection 'Non-strict execution'

---

site/en/tutorials/audio/simple_audio.ipynb

Adding an epsilon to the spectrogram before taking the log to avoid log of zero. Minor change, but it avoids confusion for students learning from the tutorial.

Avoid log of zero in plot_spectrogram

---

site/en/tutorials/images/segmentation.ipynb

##Link to the mentioned documentation
https://www.tensorflow.org/tutorials/images/segmentation

Fixed typos in image segmentation tutorial

---

site/en/tutorials/load_data/text.ipynb

Changed import statement 
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
to
from tensorflow.keras.layers import TextVectorization
Removed below note section, since experimental.preprocessing.TextVectorization moved under tensorflow.keras.layers
{
"cell_type": "markdown",
"metadata": {
"id": "HSDO9JZYrK-O"
},
"source": [
"Note: The Preprocessing APIs used in this section are experimental in TensorFlow 2.3 and subject to change."
]
},
and Changed from
preprocessing.TextVectorization
to
TextVectorization

Updated TextVectorization

---

site/en/guide/autodiff.ipynb

Notebook `guide/autodiff` has an example in the section "Intermediate results", which compute gradients with respect to a vector argument:
x = tf.constant([1, 3.0])
However, the corresponding comments on the expected gradient results refer to a scalar `x`:
print(tape.gradient(z, x).numpy())  # 108.0 (4 * x**3 at x = 3)
This patch fixes this discrepancy.

Introduction to Autodiff: Make comments consistent with corresponding code

---

site/en/tutorials/structured_data/preprocessing_layers.ipynb

Without expanding dimensions, multi-hot encoded columns are not correctly illustrated (they will be parsed as single-record multi-label, not single-label multi-record).
(Another question is whether we need multi-hot for these columns instead of one-hot, as they are not multi-label?)

expand_dims to correctly test multi-hot

---

site/en/tutorials/generative/pix2pix.ipynb
tools/tensorflow_docs/plots/__init__.py

A small typo in docstring of function _smooth in tensorflow_docs.plot __init__.py
Changed gussian to gaussian.

Typo in tensorflow_docs.plot __init__.py

---

site/en/tutorials/images/classification.ipynb

The constant can be inferred from other parts of the code.  Making this change allows for this example to be generalized more easily.

Remove a hard coded constant for the image classification tutorial.

---

site/en/guide/intro_to_graphs.ipynb

The reference to functions was broken. I changed the link to [this one](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/function.ipynb#scrollTo=i2MVoIVaNApG)

Functions reference fixed

---

site/en/tutorials/images/transfer_learning.ipynb

Fix type "evaulate" to "evaluate"

Docs: fix typo in transfer learning tutorial

---

site/en/about/bib.md

There is an extra backslash `\` character near an accented i in the bib
file that causes an invalid unicode character error when citing the 2015
tensorflow white paper in LaTeX

Fix invalid Unicode sequence in bib file

---

site/en/install/errors.md

Updated a link provided in the error section of the installation guide.The second of the links to the protobuf error wasn't found to be working either on the docs or in the related answer in the stackoverflow question.I have replaced the second with an appropriate link.Would love to know if another , more accurate link could be added.Thanks

errors:Updated a non-working link

---

site/en/install/source_windows.md

For this PR: https://github.com/tensorflow/tensorflow/pull/53864
Add a disclaimer to warn users that TF-TRT is not tested on Windows and the development team does not give any guarantees it is going to work as intended if enabled.

Add TF-TRT disclaimer for Windows builds

---

site/en/tutorials/distribute/multi_worker_with_keras.ipynb

Suggesting that the "mnist.py" file be renamed to something else like "mnist_setup.py" since the resulting "import mnist" is confusingly in conflict with the mnist package. This threw me off until I re-read the instructions, since I had placed the code in one file which resulted in errors executing mnist.mnist_dataset and mnist.build_and_compile_cnn_model.

Clarify multi_worker_with_keras.ipynb example code (#1)

---

site/en/install/source.md
site/en/install/source_windows.md

Recently when trying to build TensorFlow from source, I noticed that it started asking for the `packaging` package.

Add packaging dependency to "Build From Source" instructions

---

site/en/guide/basic_training_loops.ipynb

The function `def report` used the global variable `current_loss` instead of the functions parameter `loss`. This issue resulted in a wrong status printing:

fixed function def report in Basic training loops

---

site/en/community/contribute/code.md

**Motivation**: Went going to https://www.tensorflow.org/community/contribute/code, a link is outdated/broken. 
**Solution:** Replace with an existing link with the same contents. 
Note: when searching for "https://docs.scipy.org/doc/numpy/" inside of this repo, there are other links which are similar

Update outdated link to Git development workflow

---

site/en/tutorials/customization/custom_layers.ipynb

Fix a grammatical error within the custom layer docs:
Change "... common layers as a well as easy ways for you to ..." to "common layers as well as easy ways for you to"

Fix grammatical error in custom_layer docs

---

site/en/tutorials/keras/save_and_load.ipynb

Updated links with the correct URL path for the `checkpoint` link in the "What are these files section?" and also for `HDF5` in the "Manually saved weights section.
Earlier, the `checkpoint` link was showing the Saved model link and `HDF5` file was showing the tensorflow.js conversion model.

Updated links with correct URL path

---

site/en/tutorials/load_data/csv.ipynb

Updated and replaced the deprecated attributes max_tokens with "num_tokens" and vocab_size with "vocabulary_size" to remove the warnings from output.

Updated deprecated attributes with the new one

---

site/en/guide/ragged_tensor.ipynb

Replaced tf.substr with proper API name tf.strings.substr

Fix typo error tf.strings.substr

---

site/en/install/gpu.md

Now that TensorRT is available in the regular CUDA apt repos, the
'machine-learning' repos are no longer needed in the GPU setup instructions.

Simplify GPU install instructions.

---

site/en/guide/saved_model.ipynb

Below command for building saved_model_cli is not working  and throwing "Build file not found " error
`bazel build tensorflow/python/tools:saved_model_cli`
replaced with 
`bazel build //tensorflow/python/tools:saved_model_cli`  to make it working.  Attaching [Gist ](https://colab.sandbox.google.com/gist/mohantym/5f2785f4c21c6b1e3fe9c5958a62418d/tensorflow-ranking.ipynb#scrollTo=Gr24fRLOQVRZ)for reference.

Updated build command for saved_model_cli

---

site/en/tutorials/keras/keras_tuner.ipynb

Modified the path URLs by providing the exact direct path for `Hypermodels classes` - HyperXception and HyperResNet.

Provided direct URL path for HyperModel sub classes

---

site/en/guide/sparse_tensor.ipynb

`tf.SparseTensor` is currently an alias for `tf.sparse.SparseTensor`. Hence replaced with the more consistent alias.

`tf.SparseTensor` to `tf.sparse.SparseTensor` in sparse_tensor guide

---

site/en/tutorials/customization/basics.ipynb

Fixed typo errors by removing additional 's' in the name `tf.tensor`s to `tf.tensor`. 
Also updated the correct URL link for `tf.data.dataset` API.

Fixed some typo errors along with one link update

---

setup.py

See https://github.com/tensorflow/tensorflow/issues/56077 
Also breaking CI in Addons:
https://github.com/tensorflow/addons/pull/2721
cc @MarkDaoust

Pin compatible protobuf version

---

site/en/install/pip.md

Updated correct paths for Tensorflow Unix Python wheels
Fixes: https://github.com/tensorflow/tensorflow/issues/56330

Fixed Unix wheels URLs

---

site/en/tutorials/reinforcement_learning/actor_critic.ipynb

Added the correct link for `CartPole-v0 environment`.

Fixing the incorrect link in actor_critic.ipynb

---

site/en/tutorials/audio/music_generation.ipynb

I have updated the tf.data.dataset link with the correct URL path(https://www.tensorflow.org/api_docs/python/tf/data/Dataset). Earlier this link was routing to tensorflow datasets page.

Format tf.data.dataset in music generation tutorial, lint the doc

---

site/en/guide/distributed_training.ipynb
site/en/guide/migrate/fault_tolerance.ipynb
site/en/tutorials/distribute/custom_training.ipynb
site/en/tutorials/generative/data_compression.ipynb

**Description**
Two cells in the tensorflow data compression tutorial throw an error when run in Colab.
https://www.tensorflow.org/tutorials/generative/data_compression
**To Reproduce:**
Steps to reproduce the behavior:
1. Go to [the tutorial on colab](https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/generative/data_compression.ipynb)
2. Two cells: `plt.imshow(x)` and `plt.imshow(x_tilde)` 
3. They throw an Error: `Invalid shape (28, 28, 1) for image data` 
**Resolution:**
Simply putting a `tf.squeeze()` so that e.g. `plt.imshow(x)` -> `plt.imshow(tf.squeeze(x))` will resolve the issue.

BUGFIX: Plot shape error in tf data compression tutorial

---

site/en/tutorials/text/word2vec.ipynb

The function "generate_training_data" used the global variable "SEED" even though it takes a variable "seed" as its argument (which is also used later in the notebook). This is the code section I am talking about:
```
for target_word, context_word in positive_skip_grams:
context_class = tf.expand_dims(
tf.constant([context_word], dtype="int64"), 1)
negative_sampling_candidates, _, _ = tf.random.log_uniform_candidate_sampler(
true_classes=context_class,
num_true=1,
num_sampled=num_ns,
unique=True,
range_max=vocab_size,
seed=SEED,
name="negative_sampling")
```
I changed "SEED" to "seed" to fix the typo. No other changes were made to the notebook.

Fixed typo in generate_training_data

---

site/en/tutorials/structured_data/preprocessing_layers.ipynb

Fixed broken link for tf-idf. Changed "https://en.wikipedia.org/wiki/Tf%E2%80%93idf/" to "https://en.wikipedia.org/wiki/Tf%E2%80%93idf"

Fixed broken link

---

site/en/guide/basics.ipynb
site/en/install/pip.md

Update the pip-install page for changes to windows builds.
* Split "Windows Native" and "Windows WSL2" into two separate tabs. 
* Add a caution that "TensorFlow version, 2.10, is the last TensorFlow release that will support GPU on native-Windows". 
* Copy the linux instructions into the Windows WSL2 tab.
* Mention tensorflow-cpu + direct-ml as an option on Windows native.
The duplicated instructions use a template feature that's not supported by GitHub, but this will work on tensorflow.org/install/pip
DO_NOT_SUBMIT

Update install page for windows.

---

site/en/tutorials/distribute/custom_training.ipynb

A bullet point appeared as an asterisk in the resulting notebook due to a missing 'space' character.

Correct a bullet point, lint Custom training with tf.distribute.Strategy

---

site/en/guide/migrate/tf1_vs_tf2.ipynb

Corrected the spelling of straightforward and made changes in lines 684,134 and 162.

Fix typos in TensorFlow 1.x vs TensorFlow 2 - Behaviors and APIs guide

---

site/en/tutorials/structured_data/imbalanced_data.ipynb

Remove semi-colon symbol when plotting metrics in Classification on imbalanced data tutorial

---

site/en/guide/migrate/model_mapping.ipynb

Fixed a broken link at line 1256

Update link to Migrating model checkpoints in Use TF1.x models in TF2 workflows guide

---

site/en/tutorials/_index.yaml

Fixed broken link in XLA documentation for "Use XLA with tf.function" at line 224

Fixed broken link in XLA documentation

---

site/en/guide/gpu_performance_analysis.md
site/en/guide/migrate/canned_estimators.ipynb

Fixes depreciated API in gpu_performance_analysis at line 173 . From  experimental_steps_per_execution to steps_per_execution

Fixes depreciated API in gpu_performance_analysis

---

site/en/guide/distributed_training.ipynb

Fixed typos in lines 133 &860.

Fix a typo in the Distributed training guide

---

site/en/install/pip.md
site/en/install/source.md
site/en/install/source_windows.md
site/en/tutorials/load_data/video.ipynb

Fixed some Grammar mistakes in source.md, source_windows.md and pip.md which were found using inspect code feature of Pycharm.

Fixed some Grammar mistakes in install directory

---

site/en/guide/intro_to_graphs.ipynb

Added time unit (i.e. seconds) in `timeit.timeit()` in `intro_to_graph` to make it easily understand by users.

Added time unit (i.e. seconds) in `timeit.timeit()` in `intro_to_graph`

---

.github/workflows/bot-label-lgtm.yaml
.github/workflows/bot-nightly.yaml
.github/workflows/bot-pr-fix.yaml
.github/workflows/bot-pr-new.yaml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

site/en/guide/distributed_training.ipynb

Fixed broken links for `Keras API specifications`, `Using Model.fit`, `Sequential`, `Functional` , `subclassed` links in section 'Use tf.distribute.Strategy with Keras Model.fit'  and  for `with custom training loops` link in section 'Use tf.distribute.Strategy with custom training loops'. I have provided the .ipynb file path as mentioned in the broken link.. Please suggest in case any changes are required.

Fixed broken links

---

site/en/install/pip.md

Since TF 2.11 does't support GPU on Windows native,  updated `python3 -m pip install tensorflow` to `python3 -m pip install tensorflow=2.10` else it will always install latest release and it doesn't recognize the GPU.

Update GPU Support For Windows Native

---

site/en/tutorials/keras/overfit_and_underfit.ipynb

Passing a `loss` model into the `metrics` argument causes an error while trying to save and load the model:  
```
TypeError: __init__() got an unexpected keyword argument 'reduction' while trying to load keras model
```
Reproduce:  
1. Follow the guide and build a model
2. Save the model using `model.save(path)`
3. Load the model using `tf.keras.models.load_model(path)`

Fix metrics in `compile_and_fit`

---

site/en/tutorials/images/segmentation.ipynb

IIUC, when resizing the mask, the NEAREST NEIGHBOR interpolation method should be used to prevent the introduction of values of labels that are not present in the original mask.
Currently, if we print the values of sample mask we get:
```
>>> import numpy as np
>>> mask = iter(train_batches).next()[1]))
>>> print(np.unique(mask))
[0.0000000e+00 1.2207031e-04 3.6621094e-04 ... 1.9995728e+00 1.9999390e+00
2.0000000e+00]
```
After the change:
```
>>> import numpy as np
>>> mask = iter(train_batches).next()[1]))
>>> print(np.unique(mask))
[0. 1. 2.]
```

Use NEAREST NEIGHBOR method when resizing image mask

---

site/en/install/pip.md

No GPU support on Windows Native after TF 2.10

Update System requirements

---

site/en/tutorials/load_data/video.ipynb

There were a few cases where the dataset was referred to as UFC rather than UCF.

Fix UFC to UCF errors

---

site/en/install/pip.md

Removed broken/non existing GPU python package location for windows, since from Tensorflow 2.11, GPU instructions are different and it is mentioned in the document.

Remove GPU package location for windows

---

site/en/tutorials/load_data/images.ipynb

The `untar` argument is now deprecated in favor of `extract` according to the information at https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file. This PR replaces the `untar` argument used in this tutorial's `keras.utils.get_file` method with `extract`.

refactor: removing deprecated argument

---

site/en/tutorials/audio/simple_audio.ipynb

The [tutorial outcome](https://www.tensorflow.org/tutorials/audio/simple_audio#run_inference_on_an_audio_file) is currently confusing since the plot shows a totally different prediction than the speech file. In the graph, "go" is allegedly predicted:
This fixes the bug by using the correct variable for plot labels.
Plus minor fixes (see commit message).
Not sure

Simple audio tutorial: macOS fix, typo, do not mix label variables

---

site/en/guide/versions.md

1.   FIxed broken links in versions.md by replacing with new guides for C++, Java, Go lang 
2.  Added an element tag at line before Backward and partial forward compatibility at line 225  to make this page more  device friendly.

FIxed broken links in versions.md

---

site/en/guide/migrate/early_stopping.ipynb

Fixing a minor mistake in the documentation for early stopping with custom training loop.  The tutorial shows the best validation loss starting at 0 and being updated if the current validation loss is greater than, as opposed to less than, the best.

Fix inequality for best validation loss

---

site/en/install/lang_c.ipynb

Windows GPU libtensorflow C packages are not available in the 2.11 release. To support the community update the same to 2.10.
#Fixes https://discuss.tensorflow.org/t/windows-gpu-only-c-tensorflow-download-failure/13744/

Update Windows GPU libtensorflow C package to 2.10

---

site/en/community/contribute/code.md

Fixed group name and the corresponding hyperlink under [Issues for New Contributors](https://www.tensorflow.org/community/contribute/code#issues_for_new_contributors)

Fixed documentation in Contribute to code page

---

site/en/guide/tf_numpy.ipynb

I have updated old NumPy API link (https://numpy.org/doc/1.16) to Latest and New stable NumPy API Link (https://numpy.org/doc/stable/reference/index.html) so please do the needful. Thank you!

Updated old NumPy API Link to New one

---

site/en/r1/tutorials/load_data/tf_records.ipynb

Replaced the broken link in **tf_records.ipynb** with the right link

Fixing the broken link in tf_records.ipynb

---

site/en/install/pip.md

`python3` is not working on Windows Native. 
Changed `python3` to `python` to verify installation.

Update command to `python` for Windows Native

---

site/en/tutorials/audio/simple_audio.ipynb

The following code takes to many variables, and I have simplified the following code into more readable format. 
```py
rows = 3
cols = 3
n = rows * cols
fig, axes = plt.subplots(rows, cols, figsize=(16, 9))
for i in range(n):
if i>=n:
break
r = i // cols
c = i % cols
ax = axes[r][c]
ax.plot(example_audio[i].numpy())
ax.set_yticks(np.arange(-1.2, 1.2, 0.2))
label = label_names[example_labels[i]]
ax.set_title(label)
ax.set_ylim([-1.1,1.1])
```
to
```py
plt.figure(figsize=(16,10))
for i in range(9):
plt.subplot(3,3,i+1)
audio_signal = example_audio.numpy()[i]
plt.plot(audio_signal)
plt.title(label_names[example_labels[i]])
plt.yticks(np.arange(-1.2, 1.2, 0.2))
plt.ylim([-1.1,1.1])
```

Readable Code for Audio Signal Visualization

---

site/en/guide/tpu.ipynb

Fix broken link for sequential keras model in line 245  and  TPU Research Cloud in line 558.

Updated the broken link in tpu.ipynb

---

site/en/tutorials/load_data/video.ipynb
site/en/tutorials/structured_data/imbalanced_data.ipynb

This PR improves the tutorial for classification on imbalanced data, https://www.tensorflow.org/tutorials/structured_data/imbalanced_data:
- Add proper scoring rules
- Add choice of threshold
- Remove oversampling (to be considered a bad practice)
See also https://discuss.tensorflow.org/t/improvements-to-the-tutorial-classification-on-imbalanced-data/13520.

Improve tutorial classification on imbalanced data

---

site/en/tutorials/audio/music_generation.ipynb

_predict_next_note()_ function required _keras_model_ argument, but was using _model_ variable from parent scope.

Minor scope typo fix in music gen tutorial

---

site/en/tutorials/images/segmentation.ipynb

tf.keras.losses.CategoricalCrossentropy should be changed to tf.keras.losses.SparseCategoricalCrossentropy since the pixel classes (labels) are integers, not one-hot encoded. Code is written correct, but the markdown should fix to prevent potential confusion to readers.

fix minor typo on the image segmentation tutorial

---

site/en/tutorials/images/classification.ipynb

As mentioned in the doc https://www.tensorflow.org/api_docs/python/tf/keras/utils/get_file **untar** argument was deprecated in favor of **extract**. Replaced `untar` with `extract`

Replaced untar with extract in classification.ipynb

---

site/en/install/source.md

As per source file from r2.10 branch the tested Bazel version for Bazel builds for TF2.10v is 5.1.1. Please refer to source [file](https://github.com/tensorflow/tensorflow/blob/r2.10/.bazelversion).  
But as per documentation still Bazel version is mentioning as 5.0.0 for Linux-CPU build configuration as per [source](https://www.tensorflow.org/install/source#cpu). 
This needs to be updated to 5.1.1 as to eliminate unwanted confusion to users.

Update bazel version for Linux_CPU in source.md

---

site/en/guide/migrate/validate_correctness.ipynb

Updated the broken link for Reusing TF1.x checkpoints guide with correct link

Updated the old link to new link in validate_correctness.ipynb

---

site/en/install/lang_java_legacy.md

Fixed the broken links for 'the replacement' in line 4, 'GPU support ' in line 43 and 'previous example' in line 174

Fixed the brokenlinks in lang_java_legacy.md

---

site/en/install/pip.md

Fixes [#60183](https://github.com/tensorflow/tensorflow/issues/60183).
Modified the below lines
```
CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)")) 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib
```
with these lines of code
```
mkdir -p $CONDA_PREFIX/etc/conda/activate.d
echo 'CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))' > $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh 
echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib' >> $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
```

Update the pip.md file on how to automatically add cuda/dnn path

---

site/en/install/pip.md

The install on linux still failes if the extended docs are used, because the CUDNN_PATH variable is not set when executing the activate script
An alternative would be to use:
`echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:'"$CONDA_PREFIX/lib/:$CUDNN_PATH/lib" > $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh`
which would also be idempotent. Yet I did stick to the current suggested way of appending to the existing file.

Fix pip install docs on linux and wsl2

---

site/en/README.md

Updates the link to model-card-toolkit docs as the default branch of the model-card-toolkit repo was changed to "main".

Update link to model-card-toolkit docs

---

site/en/install/source.md

The command for installing brew for macos build instructions is outdated and returning 404 error. As suggested by @markmcd that we don't need to maintain brew installation instructions which may vary at times and we need to track it continuously. Hence I am proposing to remove the brew installation instructions as user can refer the attached link and can do on his own.
Please review and confirm whether this is OK. Thanks!

Update macos brew installation instructions from build from source

---

site/en/guide/tensor.ipynb

If the suggestion in the comment above is used as-is, the runtime returns an error due to incompatible data types.

Fix incomplete comment

---

site/en/install/pip.md

Update correct paths for Tensorflow 2.13 built wheels in documentation.

Update download links for TF 2.13

---

site/en/tutorials/images/transfer_learning.ipynb

**Typo**
Note: These layers are active only during training, when you call [Model.fit](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit). They are inactive when the model is used in inference mode in [Model.evaluate](https://www.tensorflow.org/api_docs/python/tf/keras/Model#evaluate) or **[Model.fit](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit)**.
The second reference to `Model.fit` is not intended or correct and should be changed to `Model.call` as follows:
**Correction**
Note: These layers are active only during training, when you call [Model.fit](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit). They are inactive when the model is used in inference mode in [Model.evaluate](https://www.tensorflow.org/api_docs/python/tf/keras/Model#evaluate) …

Update note in transfer_learning.ipynb related to Model.fit

---

site/en/tutorials/audio/simple_audio.ipynb

Update cuDNN and CUDA details to support latest tensorflow version (2.12).
Working Gist:
https://colab.sandbox.google.com/gist/chunduriv/faf217520a36296d07729a25b69d48ea/simple_audio.ipynb#scrollTo=AJs7HHFmg1M9

Update CUDA Details

---

site/en/guide/distributed_training.ipynb

In reference to the Keras [documentation](https://keras.io/guides/distributed_training/#singlehost-multidevice-synchronous-training) regarding single-host multi-device training, both model creation and compilation are advised to be executed within the `strategy.scope`. However, the official TensorFlow [guide](https://www.tensorflow.org/guide/distributed_training#use_tfdistributestrategy_with_keras_modelfit) shows `model.compile(...)` outside of `strategy.scope`. Possible inconsistency? Appreciate any clarification on this matter and I've opened this PR just in case. Thank you.

fix: inconsistent single host multi-device distributed guide

---

site/en/tutorials/quickstart/advanced.ipynb

In the Quickstart for experts tutorial there is the following code:
```python
class MyModel(Model):
def __init__(self):
super(MyModel, self).__init__()
```
I suggest to use `super().__init__()` instead as described everywhere else.

Quickstart advanced tutorial: simplify super().__init__() call

---

site/en/tutorials/audio/music_generation.ipynb

The parameter name is `keras_model` but the function uses `model`, updating the parameter name to match the function

Fix predict_next_note() param

---

site/en/tutorials/load_data/text.ipynb

In the Beginners tutorials > Load and preprocess data > Text, under Example 2, I believe there is an issue handling OOV tokens. The code does this:
```python
keys = vocab
values = range(2, len(vocab) + 2)  # Reserve `0` for padding, `1` for OOV tokens.
init = tf.lookup.KeyValueTensorInitializer(
keys, values, key_dtype=tf.string, value_dtype=tf.int64)
num_oov_buckets = 1
vocab_table = tf.lookup.StaticVocabularyTable(init, num_oov_buckets)
```
However, note that `StaticVocabularyTable` does not return the value 1 for OOV, but rather `hash(<term>) % num_oov_buckets + vocab_size` per its documentation. In our case, this is equal to vocab_size, which is actually 10000 (and not 1 nor 10002). This in fact collides with the token in the original index 9998. To fix this, I suggest to first map …

Loading text tutorial: fixed OOV handling

---

site/en/tutorials/load_data/text.ipynb

In the Beginners tutorials > Load and preprocess data > Text, under the "Download more datasets using TensorFlow Datasets (TFDS)" section, we do:
```python
vectorize_layer = TextVectorization(
max_tokens=VOCAB_SIZE,
output_mode='int',
output_sequence_length=MAX_SEQUENCE_LENGTH)
model = create_model(vocab_size=VOCAB_SIZE + 1, num_labels=1)
```
Since the vocabulary of the `TextVectorization` layer already includes both the padding token and OOV token (i.e. the maximum index possible is 9999 when VOCAB_SIZE is 10000), I believe the +1 should be removed from `VOCAB_SIZE + 1`. The `Embedding` layer created by `create_model` should not see a token with a value greater than 9999.

Loading text tutorial: removed +1 from VOCAB_SIZE+1

---

site/en/guide/data_performance.ipynb

I have updated the links for routing directly to the mentioned section which was not working earlier. Also changed the code format of 2 words.

Updated few links with direct URLs in data_performance.ipynb

---

site/en/tutorials/load_data/pandas_dataframe.ipynb

In the beginner's tutorials > load and process data > pandas.DataFrame there is the following code:
```python
class MyModel(tf.keras.Model):
def __init__(self):
super().__init__(self)
self.normalizer = tf.keras.layers.Normalization(axis=-1)
```
It seems like `super().__init__(self)` is incorrect here, sending `self` as one of the args to the base class `tf.keras.Model`. The documentation of `tf.keras.Model` uses `super().__init__()`, so I suggest to align it.

pandas df loading tutorial: Fix incorrect super().__init__() call

---

site/en/guide/intro_to_modules.ipynb

Added 2 lines of code `import keras`,
`@keras.saving.register_keras_serializable()` on top of the Keras Custom model definition because it shows TypeError - "Make sure custom classes are decorated with `@keras.saving.register_keras_serializable()`" while reloading the model after saving as `.keras`.
As mentioned in this Saving [Custom objects](https://www.tensorflow.org/guide/keras/serialization_and_saving#custom_objects) definition.
Please refer to this replicated working code [gist](https://colab.research.google.com/gist/RenuPatelGoogle/f124503c52144c5ed6e9c79cffcb593d/intro_to_modules.ipynb#scrollTo=hpW-4Dj3Q1Rb) for your reference. Thank you.

Added few lines of code in Keras Custom model to fix the error

---

site/en/guide/tensor.ipynb

This change should be appropriate whether the doc is viewed through:
- the web page: linked to https://www.tensorflow.org/api_docs/python/tf/dtypes
- as a notebook: ie execute dir(tf.dtypes)

Correct link to list of dtypes

---

site/en/tutorials/quickstart/beginner.ipynb

This page contains hyperlink for Mnist dataset which is actually asking for credentials now. IMO, for this page the hyperlink may not required.Hence I propose to delete the hyperlink here.
Fixes TF ticket #[62306](https://github.com/tensorflow/tensorflow/issues/62306)
Thanks!

Fix the broken link of Mnist dataset in beginner.ipynb

---

site/en/install/source.md

The documentation of source.md mentioned `cudnn` version `8.8` is needed for Tf2.15v. However, after installing that, and running TensorFlow, it complains:
2023-12-12 16:48:40.306928: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:447] Loaded runtime CuDNN library: 8.8.0 but source was compiled with: 8.9.4. CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library. If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile .
Even setup.py file contains cudnn as 8.9.4.
https://github.com/tensorflow/tensorflow/blob/0b15fdfcb3fddcb4b8a095f26d0f786e316163d7/tensorflow/tools/pip_package/setup.py#L171
Hence updating it `8.9` version(Ignoring …

Update cudnn version of TF2.15v

---

CONTRIBUTING.md
README.md

The hyperlink for `docs@tensorflow.org` not working. Updating it to `https://discuss.tensorflow.org/` as suggested by doc-Infra team.
Fixes #[62784](https://github.com/tensorflow/tensorflow/issues/62784)

Update broken link CONTRIBUTING.md

---

tools/tensorflow_docs/tools/nbfmt/__main__.py
tools/tensorflow_docs/tools/nbfmt/nbfmtmain_test.py

These fields will be used to support document-specific metadata that needs to be pushed to the publishing system.

Add support for `google` in notebook metadata.

---

site/en/install/source_windows.md

This pull request will update the https://www.tensorflow.org/install/source_windows with the steps and commands to set up the LLVM/CLANG compiler correctly and guide users on how to build TensorFlow on the Windows Platform using the CLANG compiler.

Update Windows Installation for Clang Build

---

site/en/tutorials/images/segmentation.ipynb

I've identified a couple of issues that occur under specific conditions when using TensorFlow 2.16 and Keras 3's plotting utilities, along with their respective solutions. 
- **Issue:** When executing `tf.keras.utils.plot_model(model, show_shapes=True)`, users encounter an AttributeError stating that a 'list' object has no attribute 'shape'.
- **Fix:** Enhancing the `plot_model` function call by adding keyword arguments `expand_nested=True` and `dpi=64`. This not only resolves the AttributeError but also improves the visualization output (might be a little verbose but works without needing any changes to the plotting APIs). The adjusted function call looks like this:
```python
tf.keras.utils.plot_model(model, show_shapes=True, expand_nested=True, dpi=64)
```
- **Issue:** The following …

Update the Segmentation Tutorial Colab to be compatible with Keras 3

---

site/en/guide/tpu.ipynb

Update TPU config in Use TPU notebook

---

tools/tensorflow_docs/tools/nblint/style/tensorflow.py

This would support the Gemini API cookbook style of table cell, and any other case that doesn't use the TFO classes.

Support button-cells without tfo class

---

tools/tensorflow_docs/tools/nbfmt/__main__.py

When running `pyink` (black) on a notebook with a license, it adds a space. We should permit this.

Support spaces in license headers

---

tools/tensorflow_docs/tools/nblint/style/tensorflow.py

Same as #2306 but I this time I remembered nblint.

[nblint] Support spaces in license headers

---

site/en/tutorials/images/transfer_learning.ipynb

In the Transfer_learning https://www.tensorflow.org/tutorials/images/transfer_learning, 
After running the last cell for prediction on test data with fine-tuned model, the output at the end of the code cell predicts all 1, which is wrong prediction 
**Document:**
#Apply a sigmoid since our model returns logits
predictions = tf.nn.sigmoid(predictions)
predictions = tf.where(predictions < 0.5, 0, 1)
This can be fixed by commenting/removing the part in the last cell where we apply the sigmoid function on the predictions,
#Apply a sigmoid since our model returns logits
predictions = tf.nn.sigmoid(predictions)   ======> removed this line
predictions = tf.where(predictions < 0.5, 0, 1)
The original behavior is happening because we already applied a sigmoid activation in the classification …

Fixing the wrong predictions in transfer_learning.ipynb

---

site/en/tutorials/load_data/pandas_dataframe.ipynb

Fixes: https://github.com/tensorflow/tensorflow/issues/72520

Bugfix pandas notebook.

---

.github/workflows/stale.yaml

Woops, I used spaces instead of hyphens.

Fix stale issue label

---

site/en/guide/ragged_tensor.ipynb

Addressing issue #65399 in tensorflow repo, The documentation for RaggedTensors in which it stated that 
"Ragged tensors may be passed as inputs to a Keras model by setting ragged=True on tf.keras.Input or tf.keras.layers.InputLayer." 
As there was no support for ragged tensors in the input layer as a parameter. I have altered the documentation to reflect this change and resolve the inconsistency.

Documentation Fix - Ragged Tensor

---

site/en/hub/caching.md

This file had inconsistent use of the colon mark when referring to code. Some sentences ended with the colon (":") while others had no punctuation mark.
So now the file is consistent with lines that end like:
- “through the Colab host:”
- “workarounds for this situation:”

Fixed punctuation in caching.md

---

site/en/guide/sparse_tensor.ipynb

Re-making this PR commit after updating my Google CLA and GitHub email settings to make this commit using the email address I signed with.
From [my other PR](https://github.com/tensorflow/docs/pull/2288):
A sparse matrix with shape [4, 10] is being assigned an element at location [7, 0]. This changes that to the valid [3, 0].
Thanks for your time.

(Take 2) Fix oob index in sparse example

---

site/en/install/pip.md

Specify additional steps to utilize GPU for Linux users

Specify additional steps to utilize GPU for Linux users

---

site/en/tutorials/keras/overfit_and_underfit.ipynb

Edited the compile_and_fit method in the overfit_and_underfit.ipynb notebook to correctly pass the train and val data to avoid shape mismatch error.

fixed tensorflow issue https://github.com/tensorflow/tensorflow/issues/75194

---

site/en/tutorials/keras/save_and_load.ipynb

fixed several issues in save_and_load.ipynb notebook in keras tutorials as mentioned in Tensorflow issue #75196

fixed issue https://github.com/tensorflow/tensorflow/issues/75196

---

site/en/tutorials/keras/regression.ipynb

As currently written, the one-hot encoding step leaves the user with boolean dummy values that cause errors later in the tutorial as presently written, when passing the np.array() argument to Normalization.adapt().  The values need to be cast to a numerical type (e.g., int) either at the one-hot encoding step or the adapt() step.

Update regression.ipynb to explicitly cast one-hot encoding values

---

site/en/tutorials/keras/text_classification_with_hub.ipynb

https://www.tensorflow.org/tutorials/keras/text_classification_with_hub document is failing in the Tensorflow v2.17 which contains Keras3.0. Modified the code to the Keras2.0.
Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/3f0497dc9892f933fdfd706adc39dded/text_classification_with_hub.ipynb) for the working code in Keras2.0.

Modifying the text_classification_with_hub.ipynb

---

site/en/guide/graph_optimization.ipynb

Intel Xeon 6 Processors also support fp16 with auto mixed precision optimizer

Update graph_optimization.ipynb for Intel Xeon 6 Processors

---

site/en/tutorials/audio/simple_audio.ipynb

Hi, This PR corrects a minor typo in the [simple audio tutorial notebook](https://www.tensorflow.org/tutorials/audio/simple_audio#export_the_model_with_preprocessing). The word "YOu" was changed to "You" to ensure proper grammar and readability.
Thank you for reviewing this minor fix!

Correct typo "YOu" to "You" in tutorial text

---

site/en/guide/saved_model.ipynb

Small PR - The `tensorflow/tools/proto_splitter/in-depth-guide.md` was moved to `tensorflow/tools/proto_splitter/g3doc/in-depth-guide.md`. This PR adjusts sources to changes. See here for more info: https://github.com/tensorflow/tensorflow/commit/752a1abd6ff73f654d2f9d331c722180e595ff55

Update `in-depth-guide.md` reference

---

site/en/hub/tutorials/semantic_similarity_with_tf_hub_universal_encoder.ipynb

Found one broken link in this tutorial and I have replaced it with right one.

Fixing broken link

---

site/en/tutorials/keras/text_classification.ipynb

I was walking through this tutorial in Google Colab and it wasn't working quite right. Looks like there were some issues with the paths.
1. When the tar.gz was being unzipped the original `dataset_dir` variable was missing the `_v1`
2. All the training documents were nested under a `aclImdb` folder, so included that
3. Changed occurences of `aclImdb/train` to use the `train_dir`

Update file paths in site/en/tutorials/keras/text_classification.ipynb
